temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/F3_CURP__c.field-meta.xml
<CustomField>
    <fullName>F3_CURP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CURP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ID Contrato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSap__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Número de Contrato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_ASESOR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En proceso de validación</fullName>
                </value>
                <value>
                    <fullName>C01</fullName>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>C02</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>C03</fullName>
                    <label>Cerrado</label>
                </value>
                <value>
                    <fullName>C05</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>C06</fullName>
                    <label>Bloqueado</label>
                </value>
                <value>
                    <fullName>CC01</fullName>
                    <label>Nuevo.</label>
                </value>
                <value>
                    <fullName>CC02</fullName>
                    <label>Cancelado.</label>
                </value>
                <value>
                    <fullName>CC05</fullName>
                    <label>Aprobado.</label>
                </value>
                <value>
                    <fullName>CC06</fullName>
                    <label>Bloqueado.</label>
                </value>
                <value>
                    <fullName>CC07</fullName>
                    <label>Registrado Bursanet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OD_ContractEmailCleaner_tst.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Organizacion de Datos
* Description       :   Clase test de la clase OD_ContractEmailCleaner_cls. 
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         22-Nov-2024       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
@IsTest
public class OD_ContractEmailCleaner_tst {
    
    @TestSetup
    static void setupTestData() {
        // Crear registros de para usar en las pruebas
        /* Profile perfil = [SELECT Id FROM Profile WHERE Name='Administrador del sistema' OR Name='System Administrator']; 
        User usuarioAdministrador = new User(Alias = 'userTest', Email='useradmin.actvasspro@actinver.com', 
                                                       EmailEncodingKey='UTF-8', FirstName= 'John',LastName='Blein', LanguageLocaleKey='en_US', 
                                                       LocaleSidKey='en_US', ProfileId = perfil.Id, 
                                                       TimeZoneSidKey='America/Los_Angeles', UserName='useradmin.actvasspro@actinver.com',
                                                       ID_ASESOR__c = '02030'); */

        OD_Account_cls.bypassTriggerExecution = true;
        
        Account objAcc = new Account();
        objAcc.FirstName = 'Test';
        objAcc.MiddleName = 'Test';
        objAcc.LastName = 'Test';
        objAcc.F3_CURP__c = 'TESTING1';
        objAcc.Client_ID__c = '02030';
        objAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        insert objAcc;
        
        OD_Contract_cls.bypassTriggerExecution = true;

        Contract objContract = new Contract();
        objContract.AccountId = objAcc.Id;
        objContract.ContractNumber__c = '142536';
        objContract.Status__c = 'Aprobado.';
        objContract.IDSap__c = '142536';
        insert objContract;

        Correo_de_Contrato__c objEmails = BIT_UtilityDataTest.createEmails(objContract);

        Correo_de_Contrato__c objEmailNoContract = new Correo_de_Contrato__c();
        objEmailNoContract.Name = 'Test2';
        objEmailNoContract.Contract_email__c = 'test@mail.com';
        objEmailNoContract.Principal__c = false;
        insert objEmailNoContract;

        Correo_de_Contrato__c objEmailNoStructure = new Correo_de_Contrato__c();
        objEmailNoStructure.Name = 'Test3';
        objEmailNoStructure.Contract_email__c = 'testcom';
        objEmailNoStructure.Principal__c = false;
        insert objEmailNoStructure;

    }

    @IsTest
    static void testValidateExistingRelatedContract() {
        // Recuperar datos de prueba
        Correo_de_Contrato__c correoConContrato = [SELECT Id, NUM_CONTRATO__c FROM Correo_de_Contrato__c WHERE NUM_CONTRATO__c != null LIMIT 1];
        Correo_de_Contrato__c correoSinContrato = [SELECT Id, NUM_CONTRATO__c FROM Correo_de_Contrato__c WHERE NUM_CONTRATO__c = null LIMIT 1];

        // Validar caso con contrato relacionado
        System.assertEquals(true, OD_ContractEmailCleaner_cls.ValidateExistingRelatedContract(correoConContrato), 
            'El método debería devolver true para un correo con contrato relacionado.');

        // Validar caso sin contrato relacionado
        System.assertEquals(false, OD_ContractEmailCleaner_cls.ValidateExistingRelatedContract(correoSinContrato), 
            'El método debería devolver false para un correo sin contrato relacionado.');
    }

    @IsTest
    static void testValidateAndUpdateRecords() {

        List<String> restrictedWords = Label.PalabrasRestringidas.split(',');

        // Crear correos electrónicos de prueba en función del contenido de la etiqueta
        
        String invalidEmail = restrictedWords.isEmpty() ? 
                              'scamuser@example.com' : 
                              restrictedWords[0] + 'user@example.com';
        
        Correo_de_Contrato__c objEmailRestricted = new Correo_de_Contrato__c();
        objEmailRestricted.Name = 'TestMail';
        objEmailRestricted.Contract_email__c = invalidEmail;
        objEmailRestricted.Principal__c = false;
        insert objEmailRestricted;

        // Recuperar todos los correos creados
        List<Correo_de_Contrato__c> correos = [SELECT Id, Contract_email__c, NUM_CONTRATO__c, DatoContactoNoValido__c, DatoPalabraRestringida__c FROM Correo_de_Contrato__c];

        // Validar y actualizar registros
        List<Correo_de_Contrato__c> correosToUpdate = OD_ContractEmailCleaner_cls.ValidateAndUpdateRecords(correos);

        // Comprobar los resultados esperados
        System.assert(!correosToUpdate.isEmpty(), 'La lista de correos a actualizar no debería estar vacía.');

        // Verificar que los registros inválidos sean marcados correctamente
        for (Correo_de_Contrato__c correo : correosToUpdate) {
            if (correo.Contract_email__c == invalidEmail) {
                System.assertEquals(true, correo.DatoPalabraRestringida__c, 'El correo con palabras restringidas debería ser marcado.');
            }
            if (correo.Contract_email__c == 'testcom') {
                System.assertEquals(true, correo.DatoContactoNoValido__c, 'El correo con estructura inválida debería ser marcado.');
            }
        }
    }
}