temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup Case Account  owner id</description>
    <label>Asesor de la cuenta</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Cancelacion_de_caso__c.field-meta.xml
<CustomField>
    <fullName>Cancelacion_de_caso__c</fullName>
    <inlineHelpText>Si el folio es cancelado, selecciona SI
Si el folio continua el proceso de resolución selecciona NO</inlineHelpText>
    <label>Cancelación de folio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No_sigue_proceso</fullName>
                <default>true</default>
                <label>No, sigue en proceso</label>
            </value>
            <value>
                <fullName>Si_cancela_folio</fullName>
                <label>Si, se cancela folio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Chat_ClientExternalId__c.field-meta.xml
<CustomField>
    <fullName>Chat_ClientExternalId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chat Visitor Número Cliente</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Digita los primeros números del contrato del cliente</inlineHelpText>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Submotivo__c.field-meta.xml
<CustomField>
    <fullName>Submotivo__c</fullName>
    <label>Submotivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motivo__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Reporte por robo o extravío</fullName>
            </value>
            <value>
                <fullName>Activar Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Información Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Reportar incidente</fullName>
            </value>
            <value>
                <fullName>Información Tarjeta</fullName>
            </value>
            <value>
                <fullName>Activar Bursanet</fullName>
            </value>
            <value>
                <fullName>Reportar incidente Bursanet</fullName>
            </value>
            <value>
                <fullName>Información Bursanet</fullName>
            </value>
            <value>
                <fullName>Operaciones Banco</fullName>
            </value>
            <value>
                <fullName>Operaciones CB</fullName>
            </value>
            <value>
                <fullName>Operaciones Bursanet</fullName>
            </value>
            <value>
                <fullName>Hacer una aclaración</fullName>
            </value>
            <value>
                <fullName>Seguimiento a aclaración</fullName>
            </value>
            <value>
                <fullName>Información Seguros</fullName>
            </value>
            <value>
                <fullName>Cuento con un seguro</fullName>
            </value>
            <value>
                <fullName>Información Previsión Social</fullName>
            </value>
            <value>
                <fullName>Desbloqueo o reseteo de contraseña</fullName>
            </value>
            <value>
                <fullName>Cambio o cercanía de domicilio</fullName>
            </value>
            <value>
                <fullName>Por recomendación</fullName>
            </value>
            <value>
                <fullName>Ya no labora / Sin Asesor</fullName>
            </value>
            <value>
                <fullName>Carta en Centro Financiero o Correo - Sin Motivo</fullName>
            </value>
            <value>
                <fullName>Utilizará el dinero / Temas personales</fullName>
            </value>
            <value>
                <fullName>No utiliza la cuenta / Evitar Anualidad</fullName>
            </value>
            <value>
                <fullName>Ex Empleado</fullName>
            </value>
            <value>
                <fullName>Tiene otra cuenta en Actinver</fullName>
            </value>
            <value>
                <fullName>Falta de Asesoría y/o Servicio</fullName>
            </value>
            <value>
                <fullName>Masivas</fullName>
            </value>
            <value>
                <fullName>Fallecimiento del Tìtular</fullName>
            </value>
            <value>
                <fullName>Inactividad de la Cuenta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/actiqa/objects/Case/recordTypes/CAT.recordType-meta.xml
<RecordType>
    <fullName>CAT</fullName>
    <active>true</active>
    <businessProcess>Proceso de Soporte CAT</businessProcess>
    <label>CAT</label>
</RecordType>

force-app/main/default/classes/CaseHandler.cls
/**
 * @author jiale Zhang
 * @date 11/21/2021
 * @description
 *      Used in CaseTrigger.trigger
 *      this class only used in CaseTrigger.
 * story16
 * story40
 * story41
 * issue 25
 *
 */
public without sharing class CaseHandler implements Triggers.Handler {
	List<Case> lstNewCase = (List<Case>) Trigger.new;

	List<Case> lstOldCase = (List<Case>) Trigger.old;

	Map<Id, Case> mapOldCase = (Map<Id, Case>) Trigger.oldMap;

	private static final String strEjecutivoUser = 'Ejecutivo UNE';

	private static final String strSuperviserUser = 'Supervisor UNE';

	private static final String strSysAdmin = 'System Administrator';

	private static final String strFieldOfStatus = 'Status';

	private static final String CASE_CANCELLATION = 'Si_cancela_folio';

	private static final String CASE_STATUS_CLOSED = 'Cierre';

	private static final String ERR_MSG_NOT_NEARBY = Label.ERR_MSG_NOT_NEARBY;

	private static final String ERR_MSG_CAN_NOT_REOPEN = Label.ERR_MSG_CAN_NOT_REOPEN;

	private static final String ERR_MSG_CAN_NOT_CHANGE_ASESOR = Label.ERR_MSG_CAN_NOT_CHANGE_ASESOR;

	private static final Id CASE_CAT_RT = [SELECT Id, DeveloperName FROM RecordType 
	WHERE SObjectType = 'Case' and DeveloperName = 'CAT' LIMIT 1].Id; 

	public void handle() {
		Id userProfileId = UserInfo.getProfileId();
		
		//String userType = UserInfo.getUserType();

		try {
			//String strProfileName = [SELECT name FROM profile WHERE Id = :userProfileId].Name;
			List<Profile> profiles = [SELECT name FROM Profile WHERE Id = :userProfileId];

			if (Trigger.isBefore) {
				if (Trigger.isUpdate) {
					if(profiles.size() > 0){
						String strProfileName = profiles[0].Name;
						for (Case newCase : lstNewCase) {
							Case oldCase = mapOldCase.get(newCase.Id);
							//issue 25 Asesor can't be changed
							if (strProfileName != strSysAdmin) {
								if (newCase.Asesor__c != oldCase.Asesor__c) {
									newCase.addError(ERR_MSG_CAN_NOT_CHANGE_ASESOR);
									continue;
								}
							}

							// Story 41 ：The supervisors are the only ones who can reopen the cases, the executives, once the case is closed, they will not be able to open it
							if (newCase.Status != CASE_STATUS_CLOSED && oldCase.Status == CASE_STATUS_CLOSED) {
								if (strProfileName != strSuperviserUser && strProfileName != strSysAdmin) {
									newCase.addError(ERR_MSG_CAN_NOT_REOPEN);
									continue;
								} else {
									newCase.Cancelacion_de_caso__c = null;
								}
							}

							// Story 40 ：when the picklist value of "Cancelación de Caso", is "Si, se cancela el folio", then the case should go directly to the "cierre" stage.
							if (newCase.Cancelacion_de_caso__c == CASE_CANCELLATION) {
								newCase.Status = CASE_STATUS_CLOSED;
							} /*else {
								// Story 16 ：Creation of a validation rule in the fields of each stage of the path
								if (strProfileName != strSuperviserUser && strProfileName != strSysAdmin) {
									Boolean isResult = ActinverCommon.isNearBy(newCase, strFieldOfStatus, oldCase.Status, newCase.Status);
									if (!isResult) {
										newCase.addError(ERR_MSG_NOT_NEARBY);
										continue;
									}
								}
							}*/
						}
					}
				} else if (Trigger.isInsert) {
					Set<String> setContractId = new Set<String>();
					Set<String> accountExtIds = new Set<String>();
					Map<String, Id> accountIdsMap = new Map<String, Id>();

                    for (Case objCase : lstNewCase) {
						if(objCase.Origin == 'Chat'){
							if(objCase.Chat_ClientExternalId__c != null){
								accountExtIds.add(objCase.Chat_ClientExternalId__c);
                                //Account accountReference = new Account(Client_ID__c = objCase.Chat_ClientExternalId__c);
                                //objCase.Account = new Account(Client_ID__c = String.valueOf(objCase.Chat_ClientExternalId__c));
                            }
                             
                            objCase.Type= 'Transferencia interna CAT';
							objCase.Submotivo__c = 'Consulta';
							objCase.RecordTypeId = CASE_CAT_RT;
						}

						if (!String.isEmpty(objCase.Contrato__c)) {
							setContractId.add(objCase.Contrato__c);
						}
                        //System.debug(objCase);
					}
					List<Contract> lstContract = new List<Contract>();
					if (setContractId.size() > 0) {
						lstContract = [SELECT Id, AccountId, Account.OwnerId FROM Contract WHERE Id IN :setContractId];
						//System.debug('Dio test : ' + lstContract);
					}
					Map<Id, Id> mapAccToAccOwner = new Map<Id, Id>();
					for (Contract ctract : lstContract) {
						mapAccToAccOwner.put(ctract.Id, ctract.Account.OwnerId);
					}

					//Get Accounts from Cases:
					if (accountExtIds.size() > 0) {
						for(Account acc: [SELECT Id, Client_ID__c FROM Account WHERE Client_ID__c IN:accountExtIds]){
							if(!accountIdsMap.containsKey(acc.Client_ID__c)){
								accountIdsMap.put(acc.Client_ID__c, acc.Id);
							}
						}
					}


					//System.debug('zjl test:' + mapAccToAccOwner);
					for (Case newCase : lstNewCase) {
						if(newCase.Origin == 'Chat' && newCase.Chat_ClientExternalId__c != null){
							if(accountIdsMap.containsKey(newCase.Chat_ClientExternalId__c)){
								newCase.AccountId = accountIdsMap.get(newCase.Chat_ClientExternalId__c);
							}
						}

						// Story 40 ：when the picklist value of "Cancelación de Caso", is "Si, se cancela el folio", then the case should go directly to the "cierre" stage.
						if (newCase.Cancelacion_de_caso__c == CASE_CANCELLATION) {
							newCase.Status = CASE_STATUS_CLOSED;
						}
						// issue 25 , the asesor of new Case needs to be inserted with account owner(which origins contract);
						if (!String.isEmpty(mapAccToAccOwner.get(newCase.Contrato__c))) {
							newCase.Asesor__c = mapAccToAccOwner.get(newCase.Contrato__c);
						}
					}
				}
			}
		} catch (Exception ex) {
			 System.debug('Error Msg : ' + ex.getMessage());
			 System.debug('Error Line : ' + ex.getLineNumber());
		}
	}
}