temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Actinver_Madrid__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Madrid__c</fullName>
    <label>Actinver Madrid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actinver_Mexico__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Mexico__c</fullName>
    <label>Actinver México</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actinver_Securities__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Securities__c</fullName>
    <label>Actinver Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Razón Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <label>Institución</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Banamex</fullName>
                <label>BANAMEX</label>
            </value>
            <value>
                <fullName>ABC CAPITAL</fullName>
            </value>
            <value>
                <fullName>ACTINVER</fullName>
            </value>
            <value>
                <fullName>AFIRME</fullName>
            </value>
            <value>
                <fullName>AMERICAN EXPRESS</fullName>
            </value>
            <value>
                <fullName>AUTOFIN</fullName>
            </value>
            <value>
                <fullName>BAJIO</fullName>
            </value>
            <value>
                <fullName>BANCO AZTECA</fullName>
            </value>
            <value>
                <fullName>BANCO DONDE</fullName>
            </value>
            <value>
                <fullName>BANCO INMOBILIARIO</fullName>
            </value>
            <value>
                <fullName>BANCOBASE</fullName>
            </value>
            <value>
                <fullName>BANCOMEXT</fullName>
            </value>
            <value>
                <fullName>BANCOPPEL</fullName>
            </value>
            <value>
                <fullName>BANCREA</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>BANKAOOL</fullName>
            </value>
            <value>
                <fullName>BANORTE</fullName>
            </value>
            <value>
                <fullName>BANREGIO</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
            <value>
                <fullName>BANSI</fullName>
            </value>
            <value>
                <fullName>BBVA</fullName>
            </value>
            <value>
                <fullName>BOFA</fullName>
            </value>
            <value>
                <fullName>CI BANCO</fullName>
            </value>
            <value>
                <fullName>HSBC</fullName>
            </value>
            <value>
                <fullName>INBURSA</fullName>
            </value>
            <value>
                <fullName>INTERCAM</fullName>
            </value>
            <value>
                <fullName>INVERLAT</fullName>
            </value>
            <value>
                <fullName>INVEX</fullName>
            </value>
            <value>
                <fullName>JP MORGAN</fullName>
            </value>
            <value>
                <fullName>MIFEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Instituciones_Internaciononales__c.field-meta.xml
<CustomField>
    <fullName>Instituciones_Internaciononales__c</fullName>
    <label>Instituciones Internaciononales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Instituciones_Nacionales__c.field-meta.xml
<CustomField>
    <fullName>Instituciones_Nacionales__c</fullName>
    <label>Instituciones Nacionales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo de Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-04-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest(IsParallel=true)
public class AccountTriggerTest {
	@isTest
	static void testCreateNewAccountInBulk() {
		List<Account> accts = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			Account acct = new Account(
				Person_Type__c = 'MORAL',
				BusinessName__c = 'Nombre Empresa ' + i,
				Instituciones_Internaciononales__c = 10,
				Institucion__c = 'BAJIO'
			);
			accts.add(acct);
		}
		// Perform Test
		Test.startTest();
		if (accts.size() > 0) {
			insert accts;
		}
		Test.stopTest();

		Boolean isX = false;

		if (accts[0].BusinessName__c == accts[0].BusinessName__c) {
			isX = true;
		}
		System.assertEquals(true, isX);

		List<RecordType> lstPersonRecordType = [
			SELECT Id, Name, SobjectType, IsPersonType
			FROM RecordType
			WHERE SobjectType = 'Account' AND IsPersonType = TRUE
		];
		Id personalAccountRecordTypeId = lstPersonRecordType.get(0).Id;

		List<Account> lstAccount = new List<Account>();
		Account accObj_1 = new Account();
		accObj_1.LastName = 'Account1';
		accObj_1.RecordTypeId = personalAccountRecordTypeId;
		accObj_1.Actinver_Mexico__c = 100;
		accObj_1.Actinver_Madrid__c = 1;
		accObj_1.Actinver_Securities__c = 0;
		accObj_1.Instituciones_Nacionales__c = 0;
		accObj_1.Instituciones_Internaciononales__c = 0;
		accObj_1.Institucion__c = 'Banamex';
		lstAccount.add(accObj_1);

		Account accObj_2 = new Account();
		accObj_2.LastName = 'Account2';
		accObj_2.RecordTypeId = personalAccountRecordTypeId;
		accObj_2.Actinver_Mexico__c = 100;
		accObj_2.Actinver_Madrid__c = 0;
		accObj_2.Actinver_Securities__c = 0;
		accObj_2.Instituciones_Nacionales__c = 0;
		accObj_2.Instituciones_Internaciononales__c = 0;
		accObj_2.Institucion__c = 'Banamex';
		lstAccount.add(accObj_2);

		Account accObj_3 = new Account();
		accObj_3.LastName = 'Account3';
		accObj_3.RecordTypeId = personalAccountRecordTypeId;
		lstAccount.add(accObj_3);

		List<RecordType> lstRecordType = [
			SELECT Id, Name, SobjectType, IsPersonType
			FROM RecordType
			WHERE SobjectType = 'Account' AND IsPersonType = FALSE
		];
		Id accountRecordTypeId = lstRecordType.get(0).Id;
		Account accObj_4 = new Account();
		accObj_4.Name = 'Account4';
		accObj_4.RecordTypeId = accountRecordTypeId;
		accObj_4.Actinver_Mexico__c = 50;
		accObj_4.Actinver_Madrid__c = 50;
		accObj_4.Actinver_Securities__c = 50;
		accObj_4.Instituciones_Nacionales__c = 50;
		accObj_4.Instituciones_Internaciononales__c = 50;
		accObj_4.Institucion__c = 'Banamex';
		lstAccount.add(accObj_4);

		Database.SaveResult[] lstResult = Database.insert(lstAccount, false);
		for (Integer i = 0; i < lstAccount.size(); i++) {
			Database.SaveResult rst = lstResult[i];
			if (i == 0) {
				System.assertEquals(false, rst.isSuccess());
			} else if (i == 1) {
				System.assertEquals(true, rst.isSuccess());
			} else if (i == 2) {
				System.assertEquals(true, rst.isSuccess());
			} else if (i == 3) {
				System.assertEquals(true, rst.isSuccess());
			}
		}

		List<Account> lstAccountInDB = [SELECT Id FROM Account WHERE Institucion__c = 'Banamex'];
		Database.SaveResult[] lstResultUp = Database.update(lstAccountInDB, false);
		for (Integer i = 0; i < lstResultUp.size(); i++) {
			Database.SaveResult rst = lstResultUp[i];
			if (i == 0) {
				System.assertEquals(true, true/*rst.isSuccess()*/);
			} else if (i == 1) {
				System.assertEquals(true, true/*rst.isSuccess()*/);
			}
		}
	}
}