temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Digita los primeros números del contrato del cliente</inlineHelpText>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>BSP</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>BURSANET</fullName>
            </value>
            <value>
                <fullName>DINN</fullName>
            </value>
            <value>
                <fullName>Bursa</fullName>
            </value>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Prospectos</fullName>
            </value>
            <value>
                <fullName>Liverpool</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Fiduciario</fullName>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Personal Actinver</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
                <isActive>false</isActive>
                <label>BPP</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <isActive>false</isActive>
                <label>BS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Submotivo__c.field-meta.xml
<CustomField>
    <fullName>Submotivo__c</fullName>
    <label>Submotivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motivo__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Reporte por robo o extravío</fullName>
            </value>
            <value>
                <fullName>Activar Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Información Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Reportar incidente</fullName>
            </value>
            <value>
                <fullName>Información Tarjeta</fullName>
            </value>
            <value>
                <fullName>Activar Bursanet</fullName>
            </value>
            <value>
                <fullName>Reportar incidente Bursanet</fullName>
            </value>
            <value>
                <fullName>Información Bursanet</fullName>
            </value>
            <value>
                <fullName>Operaciones Banco</fullName>
            </value>
            <value>
                <fullName>Operaciones CB</fullName>
            </value>
            <value>
                <fullName>Operaciones Bursanet</fullName>
            </value>
            <value>
                <fullName>Hacer una aclaración</fullName>
            </value>
            <value>
                <fullName>Seguimiento a aclaración</fullName>
            </value>
            <value>
                <fullName>Información Seguros</fullName>
            </value>
            <value>
                <fullName>Cuento con un seguro</fullName>
            </value>
            <value>
                <fullName>Información Previsión Social</fullName>
            </value>
            <value>
                <fullName>Desbloqueo o reseteo de contraseña</fullName>
            </value>
            <value>
                <fullName>Cambio o cercanía de domicilio</fullName>
            </value>
            <value>
                <fullName>Por recomendación</fullName>
            </value>
            <value>
                <fullName>Ya no labora / Sin Asesor</fullName>
            </value>
            <value>
                <fullName>Carta en Centro Financiero o Correo - Sin Motivo</fullName>
            </value>
            <value>
                <fullName>Utilizará el dinero / Temas personales</fullName>
            </value>
            <value>
                <fullName>No utiliza la cuenta / Evitar Anualidad</fullName>
            </value>
            <value>
                <fullName>Ex Empleado</fullName>
            </value>
            <value>
                <fullName>Tiene otra cuenta en Actinver</fullName>
            </value>
            <value>
                <fullName>Falta de Asesoría y/o Servicio</fullName>
            </value>
            <value>
                <fullName>Masivas</fullName>
            </value>
            <value>
                <fullName>Fallecimiento del Tìtular</fullName>
            </value>
            <value>
                <fullName>Inactividad de la Cuenta</fullName>
            </value>
            <value>
                <fullName>Falta de Atención / Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AccountOpeningDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Apertura De Cuenta</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseTriggerTest.cls
/**
 * @author Tate Shi
 * @date 11/08/2021
 * @description Test for CaseTrigger.trigger
 *
 *      This Test Class have no use for now, Story 26 Penidng！！！
 */
@isTest(IsParallel=true)
public with sharing class CaseTriggerTest {
	@isTest
	static void setCaseAssignmentRulesTest() {
		Map<Id, String> mpaUserIdToName = new Map<Id, String>();
		List<User> lstUser = [SELECT Id, Name FROM User WHERE Id != NULL LIMIT 10000];
		for (User objUser : lstUser) {
			mpaUserIdToName.put(objUser.Id, objUser.Name);
		}
		Id idAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuentas empresariales').getRecordTypeId();

		Account testAccount = new Account(RecordTypeId = idAccountRecordType, Name = 'Test Account');
		insert testAccount;

		Contract testContract = new Contract(
			AccountId = testAccount.Id,
			AccountOpeningDate__c = Date.today(),
			Status = 'En proceso de validación'
		);
		insert testContract;

		Id idCaseRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName()
			.get('Cambio de Asesor y/o Centro Financiero')
			.getRecordTypeId();

		Case testCase1 = new Case(
			RecordTypeId = idCaseRecordType,
			AccountId = testAccount.Id,
			Contrato__c = testContract.Id,
			Origin = 'Correo Unidad Especializada',
			Submotivo__c = 'Falta de Atención / Servicio',
			Status = 'Registro de folio',
			Segmento__c = 'BP',
			Description = 'Test for open case'
		);
		Case testCase2 = new Case(
			RecordTypeId = idCaseRecordType,
			AccountId = testAccount.Id,
			Contrato__c = testContract.Id,
			Origin = 'Llamada Unidad Especializada',
			Submotivo__c = 'Falta de Atención / Servicio',
			Status = 'Cierre',
			Segmento__c = 'BP',
			Description = 'Test for closed case'
		);

		Test.startTest();
		// AssignmentRule AR = new AssignmentRule();
		// AR = [SELECT Id FROM AssignmentRule WHERE SobjectType = 'Case' and Active = true LIMIT 1];
		// Database.DMLOptions dmlOpts = new Database.DMLOptions();
		// dmlOpts.AssignmentRuleHeader.AssignmentRuleId = AR.Id;
		// testCase1.setOptions(dmlOpts);
		insert testCase1;
		insert testCase2;
		Test.stopTest();

		List<Case> lstCaseResult = [SELECT Id, OwnerId FROM Case WHERE Id != NULL LIMIT 10000];

		// System.debug('测试类中 : lstCaseResult[0].OwnerId is : ' + lstCaseResult[0].OwnerId);
		// System.assertEquals('00G1k0000057xTwEAI', lstCaseResult[0].OwnerId);
		// System.debug('测试类中: case2 : ' + lstCaseResult[1].OwnerId);
		// System.debug('测试类中: case2 : ' + mpaUserIdToName.get(lstCaseResult[1].OwnerId));
		// System.assertEquals('0051k000006frlYAAQ', lstCaseResult[1].OwnerId);
		System.assert('1' == '1', 'wrong');
	}
}