temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FechaAntiguedad__c.field-meta.xml
<CustomField>
    <fullName>FechaAntiguedad__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha antigüedad</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PSTA_EnvioEncuestaMedallia_ctr.cls
/****************************************************************************************************
    Desarrollado por: Salvador Ramírez López (salvador.ramirez@vasscompany.com)
    Proyecto        : Actinver - Postventa
    Descripción     : Clase encargada de preparar el envío de la encuesta medallia.

    Cambios (Versiones)
    -----------------------------------------------------------------------------------------------------
    No.     Fecha           Autor                   Descripción
    -----   ----------      --------------------    -----------------------------------------------------
    1.0     2025-06-06      Salvador Ramírez        Creación de la Clase.
*/
public class PSTA_EnvioEncuestaMedallia_ctr {
    @future(callout = true)
    public static void calloutMedallia(Id idTask){
        List<Task> lstTask = PSTA_EnvioEncuestaMedallia_soql.getInfoTask(idTask);
        BIT_Medallia_Response response = new BIT_Medallia_Response();
        if(lstTask.size() > 0){
            MedalliaSurvey_Request request = new MedalliaSurvey_Request();
            Task objTask = lstTask[0];
            Map<String, Object> mapParams = new Map<String, Object>{
                'visitReason' => objTask.Type,
                'visitDate' => ACTINVER_UtilityFactory_utils.formatDate(System.today(), true),
                'userType' => 'ModeloPostventa',
                'uniqueClientId' => objTask.Account.Client_ID__c,
                'phone' => objTask.Account.Phone,
                'otherFunctions' => objTask.Subject,
                'fullName' => objTask.Account.Name,
                'financialCenter' => objTask.Account.BanqueroAsignado__r.BranchUnit.Name,
                'exitTime' => '00:00',//ACTINVER_UtilityFactory_utils.calcularEdad(objTask.Account.PersonBirthdate),
                'entryTime' => '00:00',//objTask.Account.FechaAntiguedad__c,
                'enrollmentStatus' => objTask.Account.SaldoIntegral__c,
                'email' => objTask.Account.PersonEmail,
                'contractStatus' => objTask.Account.Owner.ID_ASESOR__c,
                'contractOrigin' => 'PV' + objTask.Account.Client_ID__c + ACTINVER_UtilityFactory_utils.formatDate(System.today(), false),
                'advisorName' => objTask.Account.BanqueroAsignado__r.BusinessUnitMember.name
            };
            request = MedalliaSurvey_payload.getRequest(mapParams);
            System.debug('Request: ' + JSON.serialize(request));
            response = (BIT_Medallia_Response) Callout_cls.callService(new PostVenta_Callouts_cls.PV_EnvioEncuestaMedallia(), request);
            System.debug('Respuesta: ' + response);
        }
        //Pendiente que se termine de definir el envío de las encuestas.
    }
}