temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Area_apoyo__c.field-meta.xml
<CustomField>
    <fullName>Area_apoyo__c</fullName>
    <description>Cuando se necesita de ayuda para continuar con el proceso del caso, recurren a las áreas de apoyo</description>
    <label>Proceso de apoyo de áreas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crédito</fullName>
            </value>
            <value>
                <fullName>Jurídico</fullName>
            </value>
            <value>
                <fullName>Operaciones</fullName>
            </value>
            <value>
                <fullName>Sistemas</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Impuestos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup Case Account  owner id</description>
    <label>Asesor de la cuenta</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Cancelacion_de_caso__c.field-meta.xml
<CustomField>
    <fullName>Cancelacion_de_caso__c</fullName>
    <inlineHelpText>Si el folio es cancelado, selecciona SI
Si el folio continua el proceso de resolución selecciona NO</inlineHelpText>
    <label>Cancelación de folio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No_sigue_proceso</fullName>
                <default>true</default>
                <label>No, sigue en proceso</label>
            </value>
            <value>
                <fullName>Si_cancela_folio</fullName>
                <label>Si, se cancela folio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Centro_Financiero__c.field-meta.xml
<CustomField>
    <fullName>Centro_Financiero__c</fullName>
    <description>Branch Unit</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Centro Financiero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Digita los primeros números del contrato del cliente</inlineHelpText>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Cor_doc_apoyo__c.field-meta.xml
<CustomField>
    <fullName>Cor_doc_apoyo__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Revisión de la corrección de los documentos que realizó el área de apoyo</inlineHelpText>
    <label>Revisión de la corrección</label>
    <type>Checkbox</type>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Entidad_Federativa__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Federativa__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entidad Federativa</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Notif_Directores__c.field-meta.xml
<CustomField>
    <fullName>Notif_Directores__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Notifica a los Directores del CF origen y destino para que elaboren el formato</description>
    <label>Notificación a Directores</label>
    <type>Checkbox</type>
</CustomField>

temp/case_compare/actidev/objects/Case/fields/Recep_form_dire__c.field-meta.xml
<CustomField>
    <fullName>Recep_form_dire__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Recepción de formato firmado por directo</inlineHelpText>
    <label>Recepción de formato firmado</label>
    <type>Checkbox</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>BSP</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>BURSANET</fullName>
            </value>
            <value>
                <fullName>DINN</fullName>
            </value>
            <value>
                <fullName>Bursa</fullName>
            </value>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Prospectos</fullName>
            </value>
            <value>
                <fullName>Liverpool</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Fiduciario</fullName>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Personal Actinver</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
                <isActive>false</isActive>
                <label>BPP</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <isActive>false</isActive>
                <label>BS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/case_compare/fullcopy/objects/Case/fields/Sol_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Sol_Auditoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitud de Vo.Bo. a Auditoría</label>
    <type>Checkbox</type>
</CustomField>

temp/case_compare/actidev/objects/Case/fields/Sol_Corr__c.field-meta.xml
<CustomField>
    <fullName>Sol_Corr__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Solicitud a las áreas de apoyo por correo electrónico</description>
    <inlineHelpText>Solicitud a las áreas de apoyo por correo electrónico</inlineHelpText>
    <label>Solicitud de corrección</label>
    <type>Checkbox</type>
</CustomField>

temp/case_compare/actiqa/objects/Case/fields/Submotivo__c.field-meta.xml
<CustomField>
    <fullName>Submotivo__c</fullName>
    <label>Submotivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motivo__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
            </value>
            <value>
                <fullName>Reporte por robo o extravío</fullName>
            </value>
            <value>
                <fullName>Activar Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Información Banca Electrónica</fullName>
            </value>
            <value>
                <fullName>Reportar incidente</fullName>
            </value>
            <value>
                <fullName>Información Tarjeta</fullName>
            </value>
            <value>
                <fullName>Activar Bursanet</fullName>
            </value>
            <value>
                <fullName>Reportar incidente Bursanet</fullName>
            </value>
            <value>
                <fullName>Información Bursanet</fullName>
            </value>
            <value>
                <fullName>Operaciones Banco</fullName>
            </value>
            <value>
                <fullName>Operaciones CB</fullName>
            </value>
            <value>
                <fullName>Operaciones Bursanet</fullName>
            </value>
            <value>
                <fullName>Hacer una aclaración</fullName>
            </value>
            <value>
                <fullName>Seguimiento a aclaración</fullName>
            </value>
            <value>
                <fullName>Información Seguros</fullName>
            </value>
            <value>
                <fullName>Cuento con un seguro</fullName>
            </value>
            <value>
                <fullName>Información Previsión Social</fullName>
            </value>
            <value>
                <fullName>Desbloqueo o reseteo de contraseña</fullName>
            </value>
            <value>
                <fullName>Cambio o cercanía de domicilio</fullName>
            </value>
            <value>
                <fullName>Por recomendación</fullName>
            </value>
            <value>
                <fullName>Ya no labora / Sin Asesor</fullName>
            </value>
            <value>
                <fullName>Carta en Centro Financiero o Correo - Sin Motivo</fullName>
            </value>
            <value>
                <fullName>Utilizará el dinero / Temas personales</fullName>
            </value>
            <value>
                <fullName>No utiliza la cuenta / Evitar Anualidad</fullName>
            </value>
            <value>
                <fullName>Ex Empleado</fullName>
            </value>
            <value>
                <fullName>Tiene otra cuenta en Actinver</fullName>
            </value>
            <value>
                <fullName>Falta de Asesoría y/o Servicio</fullName>
            </value>
            <value>
                <fullName>Masivas</fullName>
            </value>
            <value>
                <fullName>Fallecimiento del Tìtular</fullName>
            </value>
            <value>
                <fullName>Inactividad de la Cuenta</fullName>
            </value>
            <value>
                <fullName>Falta de Atención / Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AccountOpeningDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Apertura De Cuenta</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseHandlerTest.cls
/**
 * @author Jiale Zhang
 * @date 11/29/2021
 * @description
 *      test CaseHandler
 */
@isTest
public with sharing class CaseHandlerTest {
	private static String strCaseStatus = 'Proceso de callback';
	private static String strTestUser = 'testUser';
	private static String strLocaleSidKey = 'es_MX';
	private static String strEmailEncodingKey = 'UTF-8';
	private static String strTimeZone1 = 'America/Mexico_City';

	@TestSetup
	static void makeData() {
		// List<User> lstUserMock = [SELECT Id,Name FROM USER WHERE Name = 'Executive UNE Test Shi'];
		List<Profile> lstProfile = [SELECT Id FROM Profile WHERE Name = 'Ejecutivo UNE'];
		User testUser = new User(
			FirstName = strTestUser,
			LastName = '1',
			UserName = 'test123321@163.com',
			Email = 'huayang.shi@pwc.com',
			Alias = 't1',
			TimeZoneSidKey = strTimeZone1,
			LocaleSidKey = strLocaleSidKey,
			EmailEncodingKey = strEmailEncodingKey,
			ProfileId = lstProfile[0].Id,
			LanguageLocaleKey = strLocaleSidKey
		);
		insert testUser;

		Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuentas empresariales').getRecordTypeId();
		Account testAccount = new Account(RecordTypeId = accountRecordTypeId, Name = 'Test Account', OwnerId = testUser.Id);
		insert testAccount;
		Contact testContact = new Contact(Email = 'jiale.zhang@pwc.com', AccountId = testAccount.Id, LastName = 'testContact');
		insert testContact;
		Contract testContract = new Contract(
			AccountId = testAccount.Id,
			AccountOpeningDate__c = Date.today(),
			Status = 'En proceso de validación'
		);
		insert testContract;

		Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
			.get('Cambio de Asesor y/o Centro Financiero')
			.getRecordTypeId();

		List<String> lstStatus = new List<String>();
		//in apex, it's a single line just means lstStatus[0] = Registro... ,lstStatus[1] = 'Proceso de re..' .....
		lstStatus.add('Registro_de_folio');
		lstStatus.add('Proceso de resolución');
		lstStatus.add(strCaseStatus);
		lstStatus.add('Cierre');

		List<Case> lstCase = new List<Case>();
		for (Integer i = 0; i < lstStatus.size(); i++) {
			String strDescription = '';
			if (i == 3) {
				strDescription = 'Test for closed case';
			} else {
				strDescription = 'Test for open case';
			}
			lstCase.add(
				new Case(
					//REQUIRED_FIELD_MISSING, Required fields are missing: [Contrato__c, Submotivo__c]: [Contrato__c, Submotivo__c]
					OwnerId = testUser.Id,
					Origin = 'Correo Unidad Especializada',
					RecordTypeId = caseRecordTypeId,
					Contrato__c = testContract.Id,
					Submotivo__c = 'Falta de Atención / Servicio',
					Status = lstStatus[i],
					Cancelacion_de_caso__c = 'No_sigue_proceso',
					Segmento__c = 'BP',
					Centro_Financiero__c = 'AGS AGUASCALIENTES NTE 509',
					Entidad_Federativa__c = 'Zacatecas',
					ContactId = testContact.Id,
					AccountId = testAccount.Id,
					Description = strDescription,
					Asesor__c = testAccount.OwnerId
				)
			);
		}
		//for test story 40 part 2
		lstCase.add(
			new Case(
				OwnerId = testUser.Id,
				Origin = 'Correo Unidad Especializada',
				RecordTypeId = caseRecordTypeId,
				Contrato__c = testContract.Id,
				Submotivo__c = 'Falta de Atención / Servicio',
				Status = strCaseStatus,
				Cancelacion_de_caso__c = 'Si_cancela_folio',
				Segmento__c = 'BP',
				Centro_Financiero__c = 'AGS AGUASCALIENTES NTE 509',
				Entidad_Federativa__c = 'Zacatecas',
				ContactId = testContact.Id,
				AccountId = testAccount.Id,
				Description = 'this is for story 40 test',
				Asesor__c = null
			)
		);
		insert lstCase;
	}
	@isTest
	public static void executecaseHandlerTest() {
		// List<User> lstUserMock = [SELECT Id,Name FROM USER WHERE Name = 'Executive UNE Test Shi'];
		List<User> lstUserMock = [SELECT Id, Name FROM USer WHERE UserName = 'test123321@163.com' LIMIT 1];
		Test.startTest();
		List<Case> lstCase = [SELECT Status, Asesor__c FROM Case WHERE Id != NULL LIMIT 10000];
		//List<Case> lstCase = [SELECT Status FROM Case];
		// System.debug('lstCase is :' + lstCase);
		System.runAs(lstUserMock[0]) {
			//test story 41 part1
			lstCase[3].Status = strCaseStatus;
			// error report update lstCase
			lstCase[3].Asesor__c = null;
			Database.update(lstCase, false);
			System.assertEquals(strCaseStatus, lstCase[3].Status);
		}
		//test story 41 part 2 (else logic)
		lstCase[3].Status = strCaseStatus;
		lstCase[3].Area_apoyo__c = 'Crédito';
		lstCase[3].Cor_doc_apoyo__c = true;
		lstCase[3].Sol_Corr__c = true;
		lstCase[3].Notif_Directores__c = true;
		lstCase[3].Recep_form_dire__c = true;
		lstCase[3].Sol_Auditoria__c = true;
		update lstCase;
		System.assertEquals(strCaseStatus, lstCase[3].Status);
		// turn back
		lstCase[3].Status = 'Cierre';
		update lstCase;
		//test story 40
		lstCase[1].Cancelacion_de_caso__c = 'Si_cancela_folio';
		update lstCase;
		System.assertEquals('Proceso de resolución', lstCase[1].Status);
		//turn back
		//lstCase[1].Status = 'Proceso de resolución';
		//update lstCase;
		System.runAs(lstUserMock[0]) {
			//test story 16
			lstCase[2].Status = 'Registro_de_folio';
			//error invoke
			//update lstCase;
			Database.update(lstCase, false);
			System.assertEquals('Registro_de_folio', lstCase[2].Status);
		}
		//test story 40 part 2;
		System.assertEquals('Cierre', lstCase[4].Status);
		// System.debug('see +++++++++++++++++++++++++++++++++++' + lstCase[1].Asesor__c + 'see +++++++++_____' + lstCase[2].Asesor__c + ' se safaweqwewq ' + lstCase[4].Asesor__c);
		Test.stopTest();
	}
}