temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaAntiguedad__c.field-meta.xml
<CustomField>
    <fullName>FechaAntiguedad__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha antigüedad</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimaVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimaVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha última visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimoContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimoContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha último contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AccountOpeningDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Apertura De Cuenta</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BanqueroAsignado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banquero Asignado</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo__c</fullName>
        <description>Saldo del contrato</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Saldo</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En proceso de validación</fullName>
                </value>
                <value>
                    <fullName>C01</fullName>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>C02</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>C03</fullName>
                    <label>Cerrado</label>
                </value>
                <value>
                    <fullName>C05</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>C06</fullName>
                    <label>Bloqueado</label>
                </value>
                <value>
                    <fullName>CC01</fullName>
                    <label>Nuevo.</label>
                </value>
                <value>
                    <fullName>CC02</fullName>
                    <label>Cancelado.</label>
                </value>
                <value>
                    <fullName>CC05</fullName>
                    <label>Aprobado.</label>
                </value>
                <value>
                    <fullName>CC06</fullName>
                    <label>Bloqueado.</label>
                </value>
                <value>
                    <fullName>CC07</fullName>
                    <label>Registrado Bursanet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeOfContract__c</fullName>
        <label>Tipo de contrato</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UN PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UNA CUENTA PERSONAL PARA EL AHORRO</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>CONTRATO MARCO DE COMPRAVENTA DE DIVISAS (BANCO)</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA ACTINVER)</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA DE NÓMINA ACTINVER)</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>TRADICIONAL DE INTERMEDIACIÓN BURSÁTIL</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>CONTRATO CUENTA LÍQUIDA ACTINVER</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Bursanet</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>Bursanet.</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Bursanet,</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>DINN</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Banco Persona Moral</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Banco Persona  Moral</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Banco  Persona Moral</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSTA_FechaPrimerContacto_cls_tst.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Post Venta
* Description       :   Clase test de la clase PSTA_FechaPrimerContacto_cls
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         23-Jul-2025       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
@isTest
public class PSTA_FechaPrimerContacto_cls_tst {
    public static final Id idConfigContratosPostVentaRecordType = Schema.SObjectType.ConfiguracionActinver__c.getRecordTypeInfosByDeveloperName().get('PSTA_ConfiguracionContratosPostventa').getRecordTypeId();
    @testSetup
    public static void testSetup() {
        ConfiguracionActinver__c config = PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        ConfiguracionActinver__c configContracts = PSTA_TestDataFactory.createConfiguracionContratosActinver();
        ConfiguracionActinver__c configContact = PSTA_TestDataFactory.createConfiguracionContactoActinver();
        User user = PSTA_TestDataFactory.createUser();
        BranchUnit branchunit = PSTA_TestDataFactory.createBranchUnit();
        Banker bankero = PSTA_TestDataFactory.createBanker(branchunit.Id, user.Id);
        BranchUnitBusinessMember banqueroAsignado = PSTA_TestDataFactory.getBranchUnitBusinessMember(bankero.Id,branchunit.Id);
        List<Account> cuentas = PSTA_TestDataFactory.createAccounts(2,banqueroAsignado.Id,true);
        List<Id> accountIds = new List<Id>();
        for(Account acc : cuentas) {
            accountIds.add(acc.Id);
        }
        List<Contract> contratos = PSTA_TestDataFactory.createContracts(accountIds,banqueroAsignado.ExternalId__c,true,banqueroAsignado.Id);
    }
@isTest
    static void testProcesarFechasConContratosValidos() {
        ConfiguracionActinver__c config = [SELECT TipoContratos__c, EstatusContrato__c 
                             FROM ConfiguracionActinver__c 
                             WHERE RecordTypeId =: idConfigContratosPostVentaRecordType 
                             LIMIT 1];
        
        //List<Account> cuentas = [SELECT Id, Name, FechaAntiguedad__c, FechaUltimoContacto__c, BanqueroAsignado__r.BusinessUnitMember FROM Account];
        List<Account> cuentas  = [SELECT Id, 
                                        FechaUltimoContacto__c,
                                        FechaUltimaVisita__c,
                                        BanqueroAsignado__c, 
                                        SaldoIntegral__c, 
                                        Segmento__c, (SELECT Id, Status__c, AccountOpeningDate__c, TypeOfContract__c, Saldo__c 
                                        FROM Contracts 
                                        WHERE Saldo__c != null AND AccountOpeningDate__c != null ORDER BY AccountOpeningDate__c ASC),
                                        TYPEOF BanqueroAsignado__r.BusinessUnitMember 
                                        WHEN Banker THEN Division__c, ExternalId__c, Id, Cargo__c 
                                        END
                                    FROM Account];
        List<Contract> contratos = [SELECT Id, AccountId, TypeOfContract__c, Status, 
                                   AccountOpeningDate__c FROM Contract 
                                   ORDER BY AccountOpeningDate__c ASC];
        
        Map<Id, List<Contract>> mapContratosPorCuenta = new Map<Id, List<Contract>>();
        for(Account acc : cuentas) {
            mapContratosPorCuenta.put(acc.Id, new List<Contract>());
        }
        for(Contract con : contratos) {
            mapContratosPorCuenta.get(con.AccountId).add(con);
        }
        
        Test.startTest();
        Map<Id, Account> cuentasParaActualizar = new Map<Id, Account>();
        //PSTA_FechaPrimerContacto_cls.procesarFechas(cuentas, mapContratosPorCuenta, cuentasParaActualizar);
        PSTA_FechaPrimerContacto_cls.procesarFechas(cuentas);
        Test.stopTest();
        
    }
    
    /*@isTest
    static void testObtenerFechaContratoMasAntiguo() {
        ConfiguracionActinver__c config = [SELECT TipoContratos__c, EstatusContrato__c 
                             FROM ConfiguracionActinver__c 
                             WHERE RecordTypeId =: idConfigContratosPostVentaRecordType 
                             LIMIT 1];
        
        List<Contract> contratos = [SELECT Id, 
                Status,
                TypeOfContract__c, 
                Saldo__c,
                AccountOpeningDate__c,
                AccountId
                FROM Contract];
        
        
        Test.startTest();
        Set<String> tiposValidos = PSTA_UtilityClass.splitValuesMultiPickList(config.TipoContratos__c);
        Set<String> estatusValidos = PSTA_UtilityClass.splitValuesMultiPickList(config.EstatusContrato__c);
        
        Date fechaResultado = PSTA_FechaPrimerContacto_cls.obtenerFechaContratoMasAntiguo(
            contratos, 
            tiposValidos, 
            estatusValidos
        );
        Test.stopTest();
        
        
    }*/
    
    
}