temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/F3_CURP__c.field-meta.xml
<CustomField>
    <fullName>F3_CURP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CURP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ID Contrato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSap__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Número de Contrato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En proceso de validación</fullName>
                </value>
                <value>
                    <fullName>C01</fullName>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>C02</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>C03</fullName>
                    <label>Cerrado</label>
                </value>
                <value>
                    <fullName>C05</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>C06</fullName>
                    <label>Bloqueado</label>
                </value>
                <value>
                    <fullName>CC01</fullName>
                    <label>Nuevo.</label>
                </value>
                <value>
                    <fullName>CC02</fullName>
                    <label>Cancelado.</label>
                </value>
                <value>
                    <fullName>CC05</fullName>
                    <label>Aprobado.</label>
                </value>
                <value>
                    <fullName>CC06</fullName>
                    <label>Bloqueado.</label>
                </value>
                <value>
                    <fullName>CC07</fullName>
                    <label>Registrado Bursanet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OD_ContractEmailThr_test.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Organizacion de Datos
* Clase 		    :   OD_ContractEmail_thr
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         22-Dic-2024       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
@IsTest
public class OD_ContractEmailThr_test {
    @testSetup
    static void testSetup() {
        OD_Account_cls.bypassTriggerExecution = true;
        
        Account objAcc = new Account();
        objAcc.FirstName = 'Test';
        objAcc.MiddleName = 'Test';
        objAcc.LastName = 'Test';
        objAcc.F3_CURP__c = 'TESTING1';
        objAcc.Client_ID__c = '02030';
        objAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        insert objAcc;
        
        OD_Contract_cls.bypassTriggerExecution = true;

        Contract objContract = new Contract();
        objContract.AccountId = objAcc.Id;
        objContract.ContractNumber__c = '142536';
        objContract.Status__c = 'Aprobado.';
        objContract.IDSap__c = '142536';
        insert objContract;

        Correo_de_Contrato__c objEmails = BIT_UtilityDataTest.createEmails(objContract);

        Correo_de_Contrato__c objEmailNoContract = new Correo_de_Contrato__c();
        objEmailNoContract.Name = 'Test2';
        objEmailNoContract.Contract_email__c = 'test@mail.com';
        objEmailNoContract.Principal__c = false;
        insert objEmailNoContract;

        Correo_de_Contrato__c objEmailNoStructure = new Correo_de_Contrato__c();
        objEmailNoStructure.Name = 'Test3';
        objEmailNoStructure.Contract_email__c = 'testcom';
        objEmailNoStructure.Principal__c = false;
        insert objEmailNoStructure;
    }

    @isTest
    static void testBeforeInsert() {
        // Probar el mapa de Ladas
        Test.startTest();
        	OD_ContractEmail_thr.beforeInsert(new List<Correo_de_Contrato__c>());
        Test.stopTest();
    }

    @isTest
    static void testBeforeUpdateBypass() {
        // Probar el mapa de Ladas
        Test.startTest();
        OD_ContractEmail_thr.bypassTriggerBeforeInsertExecution = true;
        	OD_ContractEmail_thr.beforeUpdate(new List<Correo_de_Contrato__c>(),new Map<Id, Correo_de_Contrato__c>());
        Test.stopTest();
    }

    @isTest
    static void testBeforeUpdate() {
        // Desactivar el bypass de ejecución si está activado
        Test.startTest();
        OD_ContractEmail_thr.bypassTriggerBeforeInsertExecution = false;

        // Recuperar el registro insertado en testSetup
        Correo_de_Contrato__c correo = [SELECT Id, Contract_email__c, NUM_CONTRATO__c FROM Correo_de_Contrato__c LIMIT 1];

        // Crear una versión antigua para simular Trigger.oldMap
        Map<Id, Correo_de_Contrato__c> oldMap = new Map<Id, Correo_de_Contrato__c>();
        oldMap.put(correo.Id, correo.clone(false, true)); // Clonar sin ID y con valores originales

        // Modificar los campos para activar el trigger
        correo.Contract_email__c = 'nuevo.correo@ejemplo.com';

        List<Correo_de_Contrato__c> triggerNew = new List<Correo_de_Contrato__c>{correo};

        // Llamar al método antes de la actualización
        OD_ContractEmail_thr.beforeUpdate(triggerNew, oldMap);
        Test.stopTest();

    }

}