temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EstatusContacto__c</fullName>
        <label>Etapa contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto efectivo exitoso</fullName>
                </value>
                <value>
                    <fullName>Contacto no exitoso</fullName>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cliente no quiere ser contactado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/FechaNoRequiereSerContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaNoRequiereSerContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha no requiere ser contactado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimaVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimaVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha última visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimoContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimoContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha último contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas de tipo Privada</description>
    <label>Privada</label>
</RecordType>

force-app/main/default/classes/PSTA_ListadoClientes_tst.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Salvador Ramírez López (salvador.ramirez@vasscompany.com)
* Project           :   Post Venta
* Clase principal   :   PSTA_ListadoClientes_cls
* Description       :   Clase que ejecuta
*******************************************************************************/
@isTest
public class PSTA_ListadoClientes_tst {
    @TestSetup
    static void makeData(){
        Object objConfig = PSTA_TestDataFactory.createConfiguracionContactoActinver();
        BranchUnit objBranch = PSTA_TestDataFactory.createBranchUnit();
        Banker objBanker = PSTA_TestDataFactory.createBanker(objBranch.Id, System.UserInfo.getUserId());
        BranchUnitBusinessMember objBUBM = PSTA_TestDataFactory.getBranchUnitBusinessMember(objBanker.Id, objBranch.Id);
        List<Account> lstAcc = PSTA_TestDataFactory.createAccounts(1, objBUBM.Id, true);
    }
    @isTest
    static void test_actualizarFechaSiguienteContacto(){
        Account objAcc = [SELECT ID, FechaSiguienteContacto__c, FechaUltimoContacto__c, Segmento__c FROM Account LIMIT 1];
        objAcc.FechaUltimoContacto__c = System.today();
        objAcc.Segmento__c = 'Privada';
        Account objAccCopy = new Account(FechaUltimoContacto__c = System.today().addDays(-30));
        List<Account> lstAccount = new List<Account>();
        lstAccount.add(objAcc);
        Map<Id, Account> mapAcc = new Map<Id,Account>{objAcc.Id => objAccCopy};
        Test.startTest();
            PSTA_ListadoClientes_cls.actualizarFechaSiguienteContacto(lstAccount, mapAcc);
        Test.stopTest();
    }
    @isTest
    static void test_actualizarFechaSiguienteVisita(){
        Account objAcc = [SELECT ID, FechaSiguienteVisita__c, FechaSiguienteContacto__c, Segmento__c FROM Account LIMIT 1];
        objAcc.FechaUltimaVisita__c = System.today();
        objAcc.Segmento__c = 'Privada';
        Account objAccCopy = new Account(FechaUltimaVisita__c = System.today().addDays(-30));
        List<Account> lstAccount = new List<Account>();
        lstAccount.add(objAcc);
        Map<Id, Account> mapAcc = new Map<Id,Account>{objAcc.Id => objAccCopy};
        Test.startTest();
            PSTA_ListadoClientes_cls.actualizarFechaSiguienteVisita(lstAccount, mapAcc);
        Test.stopTest();
    }
    @isTest
    static void test_actualizarFechaNoQuiereSerContactado(){
        Account objAcc = [SELECT ID, EstatusContacto__c, FechaNoRequiereSerContacto__c, Segmento__c FROM Account LIMIT 1];
        objAcc.EstatusContacto__c = 'Cliente no quiere ser contactado';
        objAcc.FechaNoRequiereSerContacto__c = System.today();
        objAcc.Segmento__c = 'Privada';
        Account objAccCopy = new Account(EstatusContacto__c = 'Contacto efectivo exitoso', FechaNoRequiereSerContacto__c = System.today().addDays(-30));
        List<Account> lstAccount = new List<Account>();
        lstAccount.add(objAcc);
        Map<Id, Account> mapAcc = new Map<Id,Account>{objAcc.Id => objAccCopy};
        Test.startTest();
            PSTA_ListadoClientes_cls.actualizarFechaNoQuiereSerContactado(lstAccount, mapAcc);
        Test.stopTest();
    }
}