temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimoContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimoContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha último contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas de tipo Privada</description>
    <label>Privada</label>
</RecordType>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AccountOpeningDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Apertura De Cuenta</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BanqueroAsignado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banquero Asignado</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo__c</fullName>
        <description>Saldo del contrato</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Saldo</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeOfContract__c</fullName>
        <label>Tipo de contrato</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UN PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UNA CUENTA PERSONAL PARA EL AHORRO</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>CONTRATO MARCO DE COMPRAVENTA DE DIVISAS (BANCO)</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA ACTINVER)</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA DE NÓMINA ACTINVER)</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>TRADICIONAL DE INTERMEDIACIÓN BURSÁTIL</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>CONTRATO CUENTA LÍQUIDA ACTINVER</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Bursanet</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>Bursanet.</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Bursanet,</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>DINN</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Banco Persona Moral</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Banco Persona  Moral</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Banco  Persona Moral</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSTA_SegmentacionClientes_cls_tst.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Post Venta
* Description       :   Clase test para la clase PSTA_SegmentacionClientes_cls
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         28-Jul-2025       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
@isTest
public class PSTA_SegmentacionClientes_cls_tst {
    @testSetup
    public static void testSetup() {
        // Configuración base
        ConfiguracionActinver__c configContratos = PSTA_TestDataFactory.createConfiguracionContratosActinver();
        ConfiguracionActinver__c configContacto = PSTA_TestDataFactory.createConfiguracionContactoActinver();
        ConfiguracionActinver__c configReactivo = PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        
        User user = PSTA_TestDataFactory.createUser();
        BranchUnit branchunit = PSTA_TestDataFactory.createBranchUnit();
        Banker bankero = PSTA_TestDataFactory.createBanker(branchunit.Id, user.Id);
        BranchUnitBusinessMember banqueroAsignado = PSTA_TestDataFactory.getBranchUnitBusinessMember(bankero.Id, branchunit.Id);
        
        // Crear cuentas con diferentes características
        List<Account> cuentas = PSTA_TestDataFactory.createAccounts(3, banqueroAsignado.Id, true);
        
        // Crear contratos asociados
        List<Id> accountIds = new List<Id>();
        for(Account acc : cuentas) {
            accountIds.add(acc.Id);
        }
        List<Contract> contratos = PSTA_TestDataFactory.createContracts(accountIds, banqueroAsignado.ExternalId__c, true, banqueroAsignado.Id);
    }

    @isTest
    static void testSegmentacionClientes_IntegracionCompleta() {
        // Obtener datos de prueba
        List<Account> cuentas = [SELECT Id,  
                  FechaUltimoContacto__c,  
                  BanqueroAsignado__c,  
                  SaldoIntegral__c,  
                  Name,  
                  Segmento__c,  
                  TYPEOF BanqueroAsignado__r.BusinessUnitMember  
                  WHEN Banker THEN Division__c, ExternalId__c, Id, Cargo__c  
                  END  FROM Account];


        Set<Id> setIdCuentas = new Set<Id>();
        for (Account acc : cuentas) {
            setIdCuentas.add(acc.Id);
        }
        List<Contract> contratos = [SELECT Id, 
                ContractNumber, 
                Status,
                TypeOfContract__c, 
                StartDate, 
                Saldo__c,
                AccountOpeningDate__c,
                AccountId
                FROM Contract
                WHERE AccountId IN :setIdCuentas];
        
        Test.startTest();
        //Map<Id, Account> resultado = PSTA_SegmentacionClientes_cls.segmentacionClientes(cuentas, contratos);
        PSTA_SegmentacionClientes_cls.segmentacionClientes(cuentas);
        Test.stopTest();
        
        
    }

    /*@isTest
    static void testOrganizarContratosPorCuenta() {
        // Obtener datos de prueba
        List<Contract> contratos = [SELECT Id, AccountId FROM Contract];
        Set<Id> accountIds = new Set<Id>();
        for(Contract con : contratos) {
            accountIds.add(con.AccountId);
        }
        
        Test.startTest();
        Map<Id, List<Contract>> resultado = PSTA_SegmentacionClientes_cls.organizarContratosPorCuenta(contratos);
        Test.stopTest();
        
        
    }*/

    @isTest
    static void testUpdateRecords_Exitoso() {
        // Crear cuentas de prueba
        List<Account> cuentas = PSTA_TestDataFactory.createAccounts(2, null, false);
        for(Account acc : cuentas) {
            acc.Segmento__c = 'Privada';
        }
        insert cuentas;
        
        Map<Id, Account> mapCuentas = new Map<Id, Account>(cuentas);
        
        Test.startTest();
        //PSTA_SegmentacionClientes_cls.updateRecords(cuentas, mapCuentas);
        PSTA_SegmentacionClientes_cls.updateRecords(cuentas);
        Test.stopTest();
        
        
    }

    @isTest
    static void testUpdateRecords_ConError() {
        // Forzar error (cuenta sin nombre requerido)
        List<Account> cuentas = new List<Account>{
            new Account(Segmento__c = 'Privada') // Falta Name que es requerido
        };
        Map<Id, Account> mapCuentas = new Map<Id, Account>();
        for(Account acc : cuentas) {
            mapCuentas.put(acc.Id, acc);
        }
        
        Test.startTest();
        //PSTA_SegmentacionClientes_cls.updateRecords(cuentas, mapCuentas);
        PSTA_SegmentacionClientes_cls.updateRecords(cuentas);
        Test.stopTest();
        
    }

    
}