temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Persona_Vulnerable__c.field-meta.xml
<CustomField>
    <fullName>Persona_Vulnerable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Persona Vulnerable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Persona_Vulnerable__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Persona_Vulnerable__c</fullName>
    <label>Tipo de Persona Vulnerable</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personas adultas mayores</fullName>
            </value>
            <value>
                <fullName>Persona con discapacidad física</fullName>
            </value>
            <value>
                <fullName>Persona con discapacidad mental</fullName>
            </value>
            <value>
                <fullName>Persona con discapacidad sensorial</fullName>
            </value>
            <value>
                <fullName>Mujer lactante</fullName>
            </value>
            <value>
                <fullName>Mujer maltrato</fullName>
            </value>
            <value>
                <fullName>Mujer en situación de explotación</fullName>
            </value>
            <value>
                <fullName>Indígenas</fullName>
            </value>
            <value>
                <fullName>Migrantes</fullName>
            </value>
            <value>
                <fullName>Discapacidad o necesidades especiales</fullName>
            </value>
            <value>
                <fullName>Víctimas de la comisión de delitos</fullName>
            </value>
            <value>
                <fullName>Alcohólicos y fármaco dependientes</fullName>
            </value>
            <value>
                <fullName>Victimas desastres naturales</fullName>
                <label>Víctimas desastres naturales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BIT_AdultoMayor_bch.cls
/**
 * @developed by      : VASS México
 * @author            : erik.romero@vasscompany.com
 * @last modified on  : 07-02-2025
 * @last modified by  : erik.romero@vasscompany.com
 * @description       : 
**/
global class BIT_AdultoMayor_bch implements Database.Batchable<sObject> {
	@testVisible
	private static Boolean isTestException = false;
	public Database.QueryLocator start (Database.BatchableContext bc) {
		String query =  Test.isRunningTest() ? System.Label.BIT_AdultoMayorSelector_test : System.Label.BIT_AdultoMayor_selector;
		return Database.getQueryLocator(query);
	}
	public void execute (Database.BatchableContext bc, list<Account> accounts) {
		List<Account> accs2Update = new List<Account>();
		for (Account acc: accounts) {
			Integer age = Date.today().year() - acc.PersonBirthdate.year();
			if (acc.PersonBirthdate.day() >= Date.today().day() && acc.PersonBirthdate.month() >= Date.today().month() && age >= 65) {
				acc.Persona_Vulnerable__c = true;
				if (acc.Tipo_de_Persona_Vulnerable__c == null) {
					acc.Tipo_de_Persona_Vulnerable__c = 'Personas adultas mayores;';
				} else if (!acc.Tipo_de_Persona_Vulnerable__c.contains('Personas adultas mayores')) {
					acc.Tipo_de_Persona_Vulnerable__c += ';Personas adultas mayores';
				}
				accs2Update.add(acc);
			}
		}
		if (!accs2Update.isEmpty()) {
			Map<String, String> mapErrors = BIT_AdultoMayor_Helper.updateAccounts(accs2Update);
			if (isTestException && Test.isRunningTest()) {
				mapErrors.put('test', 'testError');
			}
			if(!mapErrors.isEmpty()){
				BIT_AdultoMayor_Helper.saveLogError(mapErrors, 'Error al actualizar clientes', 'ERROR_BATCH_ADULTOMAYOR_001');
			}
		}
	}
	public void finish (Database.BatchableContext bc) {}
}