temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/ClienteCreadoDeProspecto__c.field-meta.xml
<CustomField>
    <fullName>ClienteCreadoDeProspecto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar cuando se crea el prospecto y cuando se convierte a cliente identificar que se convirtio desde prospecto</description>
    <label>Cliente creado de prospecto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/F3_CURP__c.field-meta.xml
<CustomField>
    <fullName>F3_CURP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CURP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/ClienteCreadoDeProspecto__c.field-meta.xml
<CustomField>
    <fullName>ClienteCreadoDeProspecto__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para identificar cuando se crea el prospecto y cuando se convierte a cliente identificar que se convirtio desde prospecto</description>
    <label>Cliente creado de prospecto</label>
    <type>Checkbox</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/CR_Rep_ConversionDate__c.field-meta.xml
<CustomField>
    <fullName>CR_Rep_ConversionDate__c</fullName>
    <description>Marca la fecha cuando un registro pasa a estado convertido</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CR_Rep_ConversionDate</label>
    <type>Date</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_Consecutivo_ID__c.field-meta.xml
<CustomField>
    <fullName>F3_Consecutivo_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Consecutivo ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_CURP__c.field-meta.xml
<CustomField>
    <fullName>F3_CURP__c</fullName>
    <description>CURP que se enviará para la generación de BP</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CURP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>F3_Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afgana</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Alandés</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albanesa</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Alemana</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorrana</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angoleña</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antártida</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Argelina</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Arubeña</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australiana AU</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>Australiana CC</label>
            </value>
            <value>
                <fullName>CX</fullName>
                <label>Australiana CX</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austríaca</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaiyana</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahameña</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahriní</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbadense</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belga</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Beliceña</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bengalí</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Beninesa</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermudeña</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorrusa</label>
            </value>
            <value>
                <fullName>MM</fullName>
                <label>Birmana</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Boliviana</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnio</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botsuanesa</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brasileña</label>
            </value>
            <value>
                <fullName>MX</fullName>
                <default>true</default>
                <label>Mexicana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/F3_RFC__c.field-meta.xml
<CustomField>
    <fullName>F3_RFC__c</fullName>
    <description>RFC  que se enviará para generar el BP</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/FinServ__ExpressedInterest__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ExpressedInterest__c</fullName>
    <label>Expressed Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinServ__ProductList</valueSetName>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Referrals</relationshipLabel>
    <relationshipName>Referral</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/FinServ__ReferredByUser__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Referrer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LeadUserReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/OportunidadDeProspecto__c.field-meta.xml
<CustomField>
    <fullName>OportunidadDeProspecto__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para saber que la oportunidad viene del prospecto cuando se crea y se convierta a cliente</description>
    <label>Oportunidad de prospecto</label>
    <type>Checkbox</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/Pais_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Pais_Nacimiento__c</fullName>
    <label>País de Nacimiento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afganistán</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Alemania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antártida</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua/Barbuda</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Antillas Hol.</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudí</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Argelia</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaiyán</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Azul</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahráin</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Bélgica</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belice</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benín</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermudas</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorrusia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia-Herz.</label>
            </value>
            <value>
                <fullName>MX</fullName>
                <default>true</default>
                <label>México</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/recordTypes/WealthManagement.recordType-meta.xml
<RecordType>
    <fullName>WealthManagement</fullName>
    <active>true</active>
    <businessProcess>Wealth Management</businessProcess>
    <description>Tipo d registro para los prospectos de Wealth management</description>
    <label>Wealth Management</label>
</RecordType>

docs/rollback/actipm-opportunity-listviews/deployed/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/F3_Consecutivo_ID__c.field-meta.xml
<CustomField>
    <fullName>F3_Consecutivo_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Consecutivo ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_RFC__c.field-meta.xml
<CustomField>
    <fullName>F3_RFC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByUser__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Referrer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunityEmployeeReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerTest.cls
/**
 * @author Tate Shi
 * @date 10/28/2021
 * @description Test Trigger : LeadTrigger and LeadHandler
 */
@isTest
public with sharing class LeadTriggerTest {
	@TestSetup
	static void makeData() {
		List<Profile> lstProfile = [SELECT Id FROM Profile WHERE Name = 'Advisor'];
		//insert User
		User testUser1 = new User(
			FirstName = 'testUser',
			LastName = '1',
			UserName = 'tttt1@163.com',
			Email = 'test1@163.com',
			Alias = 't1',
			TimeZoneSidKey = 'America/Mexico_City',
			LocaleSidKey = 'es_MX',
			EmailEncodingKey = 'UTF-8',
			ProfileId = lstProfile[0].Id,
			LanguageLocaleKey = 'es_MX'
		);
		insert testUser1;

		//insert Account : Account.OwnerId lookup(User)
		Account testAccount = new Account(FirstName = 'testAccount', LastName = '1', OwnerId = testUser1.Id);
		insert testAccount;

		//insert Opportunity : OwnerId AccountId lookup(User), AccountId lookup(Account) *OwnerId == AccountId.OwnerId
		Opportunity objOpp1 = new Opportunity(
			Name = 'TestOpp',
			StageName = 'Contacto inicial',
			CloseDate = Date.today(),
			OwnerId = testUser1.Id,
			AccountId = testAccount.Id
		);
		insert objOpp1;
        Profile wealtManagementProfile = [SELECT Id FROM Profile WHERE Name = 'Banquero Wealth Management' LIMIT 1];
		//insert User
		User testUserWM = new User(
			FirstName = 'WealtManagement',
			LastName = 'WealtManagement',
			UserName = 'WealtManagement@WM.com',
			Email = 'WealtManagement@WM.com',
			Alias = 't1',
			TimeZoneSidKey = 'America/Mexico_City',
			LocaleSidKey = 'es_MX',
			EmailEncodingKey = 'UTF-8',
			ProfileId = wealtManagementProfile.Id,
			LanguageLocaleKey = 'es_MX',
            ID_ASESOR__c = '000160371'
		);
        insert testUserWM;
        BranchUnit objBranchUnit = new BranchUnit();
        objBranchUnit.ExternalId__c = '001';
        objBranchUnit.ExternalIdBI__c ='1';
        objBranchUnit.Name = 'CF 001';
        insert objBranchUnit;
        
        Banker objBanker = new Banker();
        objBanker.Name = 'test';
        objBanker.CurrentBranchId = objBranchUnit.Id;
        objBanker.UserOrContactId = testUserWM.Id;
        objBanker.Disponible__c = true;
        objBanker.ExternalId__c = '000160371';
        insert objBanker;
        
        BranchUnitBusinessMember objBUBM =[SELECT Id,BranchUnit.ExternalId__c FROM BranchUnitBusinessMember WHERE BranchUnit.ExternalId__c =: objBranchUnit.ExternalId__c];
        objBUBM.ExternalId__c = '0001000160371';
        update objBUBM;
	}

	//Since the 53 limit is now deprecated (New limit 50,000), we only validate here that the 55 leads assigned in the test are inserted with success
	@isTest
	static void preventAssignedLeadLargerThan53TestHandlerTest() {
		Test.startTest();
		// List<User> lstUser = [SELECT Id, Name FROM User WHERE Name = 'Advisor Shi' OR Name = 'Manager Shi' OR Name = 'testUser 1'];
		List<User> lstUser = [SELECT Id, Name FROM User WHERE Name = 'testUser 1'];
		// User objBankerUser;
		// User objManagerUser;
		User objTestUser1;
		for (User objUser : lstUser) {
			if (objUser.Name == 'testUser 1') {
				objTestUser1 = objUser;
			}
		}

		List<Lead> lstLead = new List<Lead>();
		for (Integer i = 0; i < 55; i++) {
			lstLead.add(
				new Lead(
					Firstname = 'testLead',
					LastName = String.valueOf(i + 1),
					OwnerId = objTestUser1.Id,
					PostalCode = '29002',
					FinServ__ReferredByUser__c = objTestUser1.Id
				)
			);
		}
		// insert lstLead; This will fire the Trigger : LeadTrigger
		Database.SaveResult[] srList = Database.insert(lstLead, false);

		List<Lead> lstLeadResult = [SELECT Id, Name FROM Lead WHERE Id != NULL AND Firstname='testLead' LIMIT 10000];
		Test.stopTest();

		//max 53 Lead - 1 opp = 52
		System.assertEquals(
			55,
			lstLeadResult.size(),
			'As a business request, The limit changed from 53 to 50000, in order to get it back to the original limit, change the The_Max_Manual_Capacity label to 53 '
		);
		// System.assertEquals(false, srList[54].isSuccess());
		// System.assertEquals(false, srList[52].isSuccess());
		// System.assertEquals(true, srList[51].isSuccess());
		// System.assertEquals('You Can\'t have more than 53 Leads or Opportunities', srList[53].getErrors()[0].getMessage());
	}

	@isTest
	static void removeIntegrationUserLimitHandlerTest() {
		Test.startTest();
		// List<User> lstUser = [SELECT Id, Name FROM User WHERE Name = 'Advisor Shi' OR Name = 'Manager Shi' OR Name = 'testUser 1'];

		String strIntegrationUser = 'Integration User';
		if (Label.Integration_User != null) {
			strIntegrationUser = Label.Integration_User;
		}
		List<User> lstUser = [SELECT Id, Name FROM User WHERE Name = :strIntegrationUser];
		User objIntegrationUser;
		for (User objUser : lstUser) {
			if (objUser.Name == strIntegrationUser) {
				objIntegrationUser = objUser;
			}
		}

		List<Lead> lstLead = new List<Lead>();
		for (Integer i = 0; i < 55; i++) {
			lstLead.add(
				new Lead(
					Firstname = 'testLead2',
					LastName = String.valueOf(i + 1),
					OwnerId = objIntegrationUser.Id,
					PostalCode = '29002',
					FinServ__ReferredByUser__c = objIntegrationUser.Id
				)
			);
		}
		// insert lstLead; This will fire the Trigger : LeadTrigger
		Database.SaveResult[] srList = Database.insert(lstLead, false);

		List<Lead> lstLeadResult = [SELECT Id, Name FROM Lead WHERE Id != NULL AND FirstName = 'testLead2' LIMIT 10000];
		Test.stopTest();

		//max 53 Lead - 1 opp = 52
		system.debug(lstLeadResult.size());
		System.assertEquals(55, lstLeadResult.size());
		System.assertEquals(true, srList[54].isSuccess());
		System.assertEquals(true, srList[52].isSuccess());
		System.assertEquals(true, srList[51].isSuccess());
		// System.assertEquals('You Can\'t have more than 53 Leads or Opportunities', srList[53].getErrors()[0].getMessage());
	}

	@isTest
	static void TestConversionDate() {
		List<contact> lstContact = new List<Contact>();
		lstContact.add(new Contact(FirstName = 'test', LastName = 'Contact'));
		insert lstContact;
		Lead newLead = new Lead();
		newLead.FirstName = 'Test';
		newLead.LastName = 'Lead';
		newLead.PostalCode = '30000';
		newLead.Status = 'Asignado';
		newLead.FinServ__ExpressedInterest__c = 'Banca Soluciones';
		newLead.FinServ__ReferredByContact__c = lstContact[0].Id;
		newLead.F3_Consecutivo_ID__c = 'CRMPR-00000002';
		insert newLead;
		Assert.areEqual(null, newLead.CR_Rep_ConversionDate__c);
		newLead.Status = 'Cerrada Ganada';
		update newLead;
		Date conversionDate = [SELECT CR_Rep_ConversionDate__c FROM Lead WHERE Id = :newLead.id LIMIT 1].CR_Rep_ConversionDate__c;
		Assert.areEqual(System.today(), conversionDate);
	}
    @isTest
    static void testUpdateOpportunity() {
        Id recordTypeIdWM = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WealthManagement').getRecordTypeId(); 
        User testUserWM = [SELECT Id FROM USER WHERE ID_ASESOR__c = '000160371' LIMIT 1];  
                Lead newLead = new Lead();
        System.runAs(testUserWM) {     
                newLead.FirstName = 'Test';
                newLead.LastName = 'Perez';
                newLead.Suffix = 'Mendoza';
                newLead.OportunidadDeProspecto__c = true;
                newLead.LeadSource = 'Referenciado Cliente';
                newLead.F3_Nacionalidad__c = 'MX';
                newLead.Pais_Nacimiento__c = 'MX';
                newLead.F3_CURP__c = 'MOCV780623HDFSRC02';
                newLead.F3_RFC__c = 'MOCV780623';
                newLead.Email = 'josue.per@vasscompany.com';
                newLead.ClienteCreadoDeProspecto__c = true;
                newLead.Status = 'Contactado';
                newLead.Estado_Nacimiento__c = 'CHS';
                newLead.Prioridad__c = 'Baja';
                newLead.MobilePhone = '5544332299';
                newLead.Clasificacion_Persona__c = '4';
                newLead.MontoEstimadoDeInversion__c = 123;
                newLead.FechaEstimadaDeCierre__c = System.today().addDays(1);
                newLead.F3_Estado_Civil__c = '2';
                newLead.Fecha_Nacimiento_Prospecto__c = System.today().addyears(-40);
                newLead.Gender__c = '1';
                newLead.Tipo_de_Persona__c = '1';
                newLead.RecordTypeId = recordTypeIdWM;
                //newLead.OwnerId = testUserWM.Id;
                newLead.F3_Consecutivo_ID__c = 'CRMPR-00000099';
                insert newLead;
        }
        //Lead updateLead = [SELECT Id, F3_Consecutivo_ID__c FROM Lead WHERE F3_Consecutivo_ID__c = 'CRMPR-00000099' LIMIT 1];
        //System.debug('########### updateLead'+newLead);
		Test.startTest();
        try{
        	LeadTrigger_Helper.updateOpportunity(newLead);
        }catch(Exception ex){
            System.debug('Error controlado en test: ' +ex);
            System.debug('Error inesperado: ' + ex.getMessage() + ' - Línea: ' + ex.getLineNumber());
 
        }
        Test.stopTest();
    }
	@isTest
    static void testUpdateLead() {
        Id recordTypeIdWM = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WealthManagement').getRecordTypeId(); 
        User testUserWM = [SELECT Id FROM USER WHERE ID_ASESOR__c = '000160371' LIMIT 1];
                Lead newLead = new Lead();
        System.runAs(testUserWM) {       
                newLead.FirstName = 'Test';
                newLead.LastName = 'Perez';
                newLead.Suffix = 'Mendoza';
                newLead.OportunidadDeProspecto__c = true;
                newLead.LeadSource = 'Referenciado Cliente';
                newLead.F3_Nacionalidad__c = 'MX';
                newLead.Pais_Nacimiento__c = 'MX';
                newLead.F3_CURP__c = 'MOCV780623HDFSRC02';
                newLead.F3_RFC__c = 'MOCV780623';
                newLead.Email = 'josue.per@vasscompany.com';
                newLead.ClienteCreadoDeProspecto__c = true;
                newLead.Status = 'Contactado';
                newLead.Estado_Nacimiento__c = 'CHS';
                newLead.Prioridad__c = 'Baja';
                newLead.MobilePhone = '5544332299';
                newLead.Clasificacion_Persona__c = '4';
                newLead.MontoEstimadoDeInversion__c = 123;
                newLead.FechaEstimadaDeCierre__c = System.today().addDays(1);
                newLead.F3_Estado_Civil__c = '2';
                newLead.Fecha_Nacimiento_Prospecto__c = System.today().addyears(-40);
                newLead.Gender__c = '1';
                newLead.Tipo_de_Persona__c = '1';
                newLead.RecordTypeId = recordTypeIdWM;
                //newLead.OwnerId = testUserWM.Id;
                newLead.F3_Consecutivo_ID__c = 'CRMPR-00000099';
                insert newLead;
        }
        //Lead updateLead = [SELECT Id, F3_Consecutivo_ID__c FROM Lead WHERE F3_Consecutivo_ID__c = 'CRMPR-00000099' LIMIT 1];
        //System.debug('########### updateLead'+updateLead);
        String[] leadIds = new List<String>{newLead.Id};
		Test.startTest();
        try{
        	LeadTrigger_Helper.updateLead(leadIds);
        }catch(Exception ex){
            System.debug('Error controlado en test: ' +ex);
            System.debug('Error inesperado: ' + ex.getMessage() + ' - Línea: ' + ex.getLineNumber());
 
        }
        Test.stopTest();
    }
    
	@isTest
    static void testGetAccountByLead() {
		Test.startTest();
        try{
        	LeadTrigger_Helper.getAccountByLead(new List<String>());
        }catch(Exception ex){
            System.debug('Error controlado en test: ' +ex);
            System.debug('Error inesperado: ' + ex.getMessage() + ' - Línea: ' + ex.getLineNumber());
 
        }
        Test.stopTest();

    }
    
	@isTest
    static void testGetOpportunityByAccount() {
		Test.startTest();
        try{
        	LeadTrigger_Helper.getOpportunityByAccount('');
        }catch(Exception ex){
            System.debug('Error controlado en test: ' +ex);
            System.debug('Error inesperado: ' + ex.getMessage() + ' - Línea: ' + ex.getLineNumber());

        }
        Test.stopTest();

    }
    
	@isTest
    static void testInsertLeadWM() {
        Id recordTypeIdWM = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WealthManagement').getRecordTypeId(); 
        User testUserWM = [SELECT Id FROM USER WHERE ID_ASESOR__c = '000160371' LIMIT 1];
        System.runAs(testUserWM) {       
                Lead newLead = new Lead();
                newLead.FirstName = 'Test';
                newLead.LastName = 'Perez';
                newLead.Suffix = 'Mendoza';
                newLead.OportunidadDeProspecto__c = true;
                newLead.LeadSource = 'Referenciado Cliente';
                newLead.F3_Nacionalidad__c = 'MX';
                newLead.Pais_Nacimiento__c = 'MX';
                newLead.F3_CURP__c = 'MOCV780623HDFSRC02';
                newLead.F3_RFC__c = 'MOCV780623';
                newLead.Email = 'josue.per@vasscompany.com';
                newLead.ClienteCreadoDeProspecto__c = true;
                newLead.Status = 'Contactado';
                newLead.Estado_Nacimiento__c = 'CHS';
                newLead.Prioridad__c = 'Baja';
                newLead.MobilePhone = '5544332299';
                newLead.Clasificacion_Persona__c = '4';
                newLead.MontoEstimadoDeInversion__c = 123;
                newLead.FechaEstimadaDeCierre__c = System.today().addDays(1);
                newLead.F3_Estado_Civil__c = '2';
                newLead.Fecha_Nacimiento_Prospecto__c = System.today().addyears(-40);
                newLead.Gender__c = '1';
                newLead.Tipo_de_Persona__c = '1';
                newLead.RecordTypeId = recordTypeIdWM;
                //newLead.OwnerId = testUserWM.Id;
                newLead.F3_Consecutivo_ID__c = 'CRMPR-00000099';
                insert newLead;
        }
    }
}