temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactoPriorizadoEsteMes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacto priorizado este mes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PriorizacionContacto__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Priorización de contacto</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PriorizacionVisita__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PriorizaciónVisita</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaAntiguedad__c.field-meta.xml
<CustomField>
    <fullName>FechaAntiguedad__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha antigüedad</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimaVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimaVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha última visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimoContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimoContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha último contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AccountOpeningDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha Apertura De Cuenta</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BanqueroAsignado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banquero Asignado</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo__c</fullName>
        <description>Saldo del contrato</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Saldo</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSTA_FechaPrimerContacto_cls.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Post Venta
* Clase test		:   PSTA_FechaPrimerContacto_cls_tst
* Description       :   Clase helper que actualiza la fecha de ultimo contacto de la cuenta en caso de no tener con la fecha de apertura del primer contrato
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         16-Jun-2025       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
public class PSTA_FechaPrimerContacto_cls {

    public static List<Account> procesarFechas(List<Account> lstCuentas) {

        
        for(Account cuenta : lstCuentas) {
            System.debug('#Contratos: '+cuenta.contracts.size());
            
            Banker banker = (Banker)cuenta.BanqueroAsignado__r.BusinessUnitMember;
            if (PSTA_Segmentacion_cls.determinarSegmento(banker) == null) {
                continue;
            }

            cuenta.Segmento__c = PSTA_Segmentacion_cls.determinarSegmento(banker);
            if(cuenta.contracts.size() > 0) {
                Decimal saldoTotal = 0;
                for(Contract contrato : cuenta.contracts) {
                    saldoTotal += Decimal.valueOf(contrato.Saldo__c);
                }

                cuenta.SaldoIntegral__c = saldoTotal;
            

                Date fechaMasAntigua = cuenta.contracts[0].AccountOpeningDate__c;
                cuenta.FechaAntiguedad__c = fechaMasAntigua;

                if(cuenta.FechaUltimoContacto__c == null) {
                    cuenta.FechaUltimoContacto__c   = fechaMasAntigua != null ? fechaMasAntigua : cuenta.FechaUltimoContacto__c;
                    cuenta.FechaUltimaVisita__c     = fechaMasAntigua != null ? fechaMasAntigua : cuenta.FechaUltimaVisita__c;
                }
                
            }


            cuenta.ContactoPriorizadoEsteMes__c = false;
            cuenta.PriorizacionContacto__c      = false;
            cuenta.PriorizacionVisita__c        = false;

        }
        return lstCuentas;
    }
    
    

}