temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EstatusContacto__c</fullName>
        <label>Etapa contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto efectivo exitoso</fullName>
                </value>
                <value>
                    <fullName>Contacto no exitoso</fullName>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cliente no quiere ser contactado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaNoRequiereSerContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaNoRequiereSerContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha no requiere ser contactado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimaVisita__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimaVisita__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha última visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PSTA_Account_thr_tst.cls
/***************************************************************************************
Desarrollado por:        VASS México
Autor:                   Jessica Salazar 
Proyecto:                Actinver Postventa
Descripción:             Clase test para PSTA_Account_thr
------------------------------------------------------------------------------------------
No.        Fecha               Autor                             Descripción
------  ----------  -----------------------------    -------------------------------------
1.0     15-07-2025        Jessica Salazar                         Creación
*******************************************************************************************/
@IsTest
public class PSTA_Account_thr_tst {
    
    @isTest
    static void test_onBeforeUpdate() {
        OD_Account_cls.bypassTriggerExecution = true;
        Account acc = new Account(
            Name = 'Cliente de Prueba',
            saldointegral__c = 1000,
            FechaNoRequiereSerContacto__c = Date.today(),
            FechaSiguienteContacto__c = Date.today(),
            FechaSiguienteVisita__c = Date.today(),
            FechaUltimaVisita__c = Date.today().addDays(-10),
            EstatusContacto__c = 'Contacto efectivo exitoso'
        );
        insert acc;

        acc = [SELECT Id, Name, saldointegral__c, FechaNoRequiereSerContacto__c, 
                      FechaSiguienteContacto__c, FechaSiguienteVisita__c, FechaUltimaVisita__c, EstatusContacto__c,  BanqueroAsignado__c, Owner.Id
               FROM Account
               WHERE Id = :acc.Id];

        Account updatedAcc = new Account(
            Id = acc.Id,
            saldointegral__c = 2000,
            FechaNoRequiereSerContacto__c = acc.FechaNoRequiereSerContacto__c,
            FechaSiguienteContacto__c = acc.FechaSiguienteContacto__c,
            FechaSiguienteVisita__c = acc.FechaSiguienteVisita__c,
            FechaUltimaVisita__c = acc.FechaUltimaVisita__c,
            EstatusContacto__c = acc.EstatusContacto__c,
            BanqueroAsignado__c = acc.BanqueroAsignado__c
        );

        List<Account> newList = new List<Account>{ updatedAcc };
        Map<Id, Account> oldMap = new Map<Id, Account>{ acc.Id => acc };

        ConfiguracionActinver__c config = PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        Test.startTest();
        PSTA_Account_thr.onBeforeUpdate(newList, oldMap);
        Test.stopTest();
    }
}