temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Actinver_Madrid__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Madrid__c</fullName>
    <label>Actinver Madrid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actinver_Mexico__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Mexico__c</fullName>
    <label>Actinver México</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actinver_Securities__c.field-meta.xml
<CustomField>
    <fullName>Actinver_Securities__c</fullName>
    <label>Actinver Securities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Razón Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Instituciones_Internaciononales__c.field-meta.xml
<CustomField>
    <fullName>Instituciones_Internaciononales__c</fullName>
    <label>Instituciones Internaciononales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Instituciones_Nacionales__c.field-meta.xml
<CustomField>
    <fullName>Instituciones_Nacionales__c</fullName>
    <label>Instituciones Nacionales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_Completo_Actinver__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Completo_Actinver__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nombre Completo Actinver</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo de Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTrigger_Helper.cls
public with sharing class AccountTrigger_Helper {
	public static void createAccounts(List<Account> accts) {
		for (Account a : accts) {
			if (a.Person_Type__c == 'MORAL') {
				a.Name = a.BusinessName__c;
				a.PersonBirthdate = null;
				System.debug(JSON.serializePretty(a));
			}
			if (a.Person_Type__c == 'FISICA') {
				if (a.Nombre_Completo_Actinver__c != null) {
					a.FirstName = a.Nombre_Completo_Actinver__c.length() >= 40
						? a.Nombre_Completo_Actinver__c.substring(0, 39)
						: a.Nombre_Completo_Actinver__c;
				}
			}
		}
	}

	/**
	 * Check if the total percentage is above 100%
	 */
	public static void checkTotalPercent(List<Account> accts) {
		Decimal decActinverMexico = 0;
		Decimal decActinverMadrid = 0;
		Decimal decActinverSecurities = 0;
		Decimal decInstitucionesNacionales = 0;
		Decimal decInstitucionesInternaciononales = 0;

		for (Account accObj : accts) {
			// if all the fields are null, skip the check
			if (
				accObj.Actinver_Mexico__c == null &&
				accObj.Actinver_Madrid__c == null &&
				accObj.Actinver_Securities__c == null &&
				accObj.Instituciones_Nacionales__c == null &&
				accObj.Instituciones_Internaciononales__c == null
			) {
				continue;
			}

			// Only persona accout need this check
			if (accObj.IsPersonAccount) {
				decActinverMexico = (accObj.Actinver_Mexico__c == null) ? 0 : accObj.Actinver_Mexico__c;
				decActinverMadrid = (accObj.Actinver_Madrid__c == null) ? 0 : accObj.Actinver_Madrid__c;
				decActinverSecurities = (accObj.Actinver_Securities__c == null) ? 0 : accObj.Actinver_Securities__c;
				decInstitucionesNacionales = (accObj.Instituciones_Nacionales__c == null) ? 0 : accObj.Instituciones_Nacionales__c;
				decInstitucionesInternaciononales = (accObj.Instituciones_Internaciononales__c == null)
					? 0
					: accObj.Instituciones_Internaciononales__c;

				if (
					(decActinverMexico +
					decActinverMadrid +
					decActinverSecurities +
					decInstitucionesNacionales +
					decInstitucionesInternaciononales) != 100
				) {
					accObj.addError(Label.CheckTotalPercent);
				}
			}
		}
	}
}