temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas de tipo Privada</description>
    <label>Privada</label>
</RecordType>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_isCreatedInSAP__c.field-meta.xml
<CustomField>
    <fullName>F3_isCreatedInSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Creado en SAP</label>
    <type>Checkbox</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_Se_completaron_campos_minimos__c.field-meta.xml
<CustomField>
    <fullName>F3_Se_completaron_campos_minimos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Se completaron campos mínimos?</label>
    <type>Checkbox</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/Fecha_Nacimiento_Prospecto__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento_Prospecto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha de Nacimiento Prospecto</label>
    <type>Date</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <businessProcess>Privada</businessProcess>
    <label>Privada</label>
</RecordType>

temp/onboarding_retrieve/qa/objects/Lead/recordTypes/WealthManagement.recordType-meta.xml
<RecordType>
    <fullName>WealthManagement</fullName>
    <active>true</active>
    <businessProcess>Wealth Management</businessProcess>
    <description>Tipo d registro para los prospectos de Wealth management</description>
    <label>Wealth Management</label>
</RecordType>

docs/rollback/actipm-opportunity-listviews/deployed/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/F3_isCreatedInSAP__c.field-meta.xml
<CustomField>
    <fullName>F3_isCreatedInSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Creado en SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_Se_completaron_campos_mInimos__c.field-meta.xml
<CustomField>
    <fullName>F3_Se_completaron_campos_mInimos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Se completaron campos mínimos?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_de_Nacimiento_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento_Cliente__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Patrimonial.recordType-meta.xml
<RecordType>
    <fullName>Patrimonial</fullName>
    <active>true</active>
    <businessProcess>Patrimonial</businessProcess>
    <description>Tipo de registro para el segmento de patrimonial</description>
    <label>Patrimonial</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <businessProcess>Privada</businessProcess>
    <label>Privada</label>
</RecordType>

force-app/main/default/classes/F3_SendDataToSAP_Handler.cls
/**
 *   ------------------------------------------------------------------------------------------------
 * @Name     F3_SendDataToSAP_Controller
 * @Author   luis.felipe.ortiz@pwc.com
 * @Date     Created: 19/10/2022
 * @Group    PWC
 * ------------------------------------------------------------------------------------------------
 * @Description Handler class for the F3_SendDataToSAP_Controller class
 * ------------------------------------------------------------------------------------------------
 * @Changes
 * 19/10/2022 luis.felipe.ortiz@pwc.com
 *             Class creation.
 * ------------------------------------------------------------------------------------------------
 **/
public with sharing class F3_SendDataToSAP_Handler {
	Public static String WS_CREATE_CLIENT_SAP_OLD  = 'crearClienteContrato';
	Public static String WS_CREATE_CLIENT_SAP_NEW  = 'crearClienteContrato_NewLed';
	Public static String DEVELOPER_NAME_RT_WM = 'WealthManagement';
    Public static String DEVELOPER_NAME_RT_PATR = 'Patrimonial';
	Public static String DEVELOPER_NAME_RT_PRIVADA = 'Privada';
	static public Integration_Service.ServiceResponse sendLeads(List<String> leadsIds, Boolean FieldsCompleted, String strPatrimonialSettings, String strQuery) {
		String nameSettingWS = '';
		try {
			List<Lead> leadsToUpdate = new List<Lead>();
            Id recordId = leadsids[0];
            String sObjectType = recordId.getSObjectType().getDescribe().getName();
            strQuery = sObjectType =='Lead' ? 'SELECT ' + strQuery + ' FROM Lead WHERE Id IN :leadsIds' : 'SELECT ' + strQuery + ' FROM Opportunity WHERE Id IN :leadsIds';
            System.debug('sobjectype: ' + sObjectType + ' list ids: '+ leadsIds);
			List<Integration_Service.ServiceResponse> responseList = new List<Integration_Service.ServiceResponse>();
			for(sObject[] sObj : Database.query(strQuery)) {
				Map<String, Object> leadMap = sObj[0].getPopulatedFieldsAsMap().clone();
				RecordType objRecordType    = (RecordType) leadMap.get('RecordType');
				if (leadMap.containsKey('Fecha_Nacimiento_Prospecto__c') || leadMap.containsKey('Fecha_de_Nacimiento_Cliente__c')) {
					Date leadBornDate = leadMap.get('Fecha_Nacimiento_Prospecto__c') == null ? (Date) leadMap.get('Fecha_de_Nacimiento_Cliente__c') : (Date) leadMap.get('Fecha_Nacimiento_Prospecto__c');
                    //Date leadBornDate = (Date) leadMap.get('Fecha_Nacimiento_Prospecto__c');
					String leadBornDateDay = String.valueOf(leadBornDate.day()).length() == 1 ? '0' + leadBornDate.day() : String.valueOf(leadBornDate.day());
					String leadBornDateMonth = String.valueOf(leadBornDate.month()).length() == 1 ? '0' + leadBornDate.month() : String.valueOf(leadBornDate.month());
					leadMap.put('Fecha_Nacimiento_Prospecto__c', '' + leadBornDate.year() + leadBornDateMonth + leadBornDateDay);
					leadMap.put('Fecha_de_Nacimiento_Cliente__c', '' + leadBornDate.year() + leadBornDateMonth + leadBornDateDay);
				}
                System.debug('MAPA OBJETO: ' + leadMap);
				Integration_Service.ServiceResponse response = Integration_Service.calloutService(
					strPatrimonialSettings,
					null,
					null,
					leadMap,
					false
				);
				response.serviceHeaders = null;
				response.logger = null;
				responseList.add(response);
				if(objRecordType.Developername != DEVELOPER_NAME_RT_WM && objRecordType.Developername != DEVELOPER_NAME_RT_PRIVADA && objRecordType.Developername != DEVELOPER_NAME_RT_PATR) leadsToUpdate.add(fieldUpdateLead(response,leadMap,fieldsCompleted));
			}
			if (!leadsToUpdate.isEmpty())  update leadsToUpdate;
			System.debug('####response: '+ responseList[0]);
			return responseList[0];
		} catch (Exception e) {
            System.debug('####ERROR CLASS F3_SendDataToSAP_Handler: '+ e.getMessage() + ' LINE: ' +e.getLineNumber());
			throw new F3_RestServices_Exception(e.getMessage());
		}
	}

	static public String sendOpps(List<String> oppsIds) {
		List<Opportunity> oppsList = Database.query(
			'SELECT ' + System.Label.crearActualizarContrato_Fields + ' FROM Opportunity WHERE Id IN :oppsIds'
		);
		Map<String, Object> oppMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(oppsList[0].getPopulatedFieldsAsMap()));
		oppMap.put('Owner.ID_ASESOR__c', ((Map<String, Object>) oppMap.get('Owner')).get('ID_ASESOR__c'));
		oppMap.put('Account.Client_ID__c', ((Map<String, Object>) oppMap.get('Account')).get('Client_ID__c'));
		try {
			Integration_Service.ServiceResponse response = Integration_Service.calloutService(
				'crearActualizarContrato',
				null,
				null,
				oppMap,
				false
			);
			if (String.valueOf(response.serviceCode).startsWithIgnoreCase('2')) {
				String updatedLeads = F3_SendDataToSAP_Helper.updateOpps(oppsIds);
			}

			system.debug(JSON.serializePretty(response));
			response.serviceHeaders = null;
			response.logger = null;
			return JSON.serialize(response);
		} catch (Exception e) {
			throw new F3_RestServices_Exception(e.getMessage());
		}
	}

	static public String getAccount(String accountBP) {
		Set<String> insertedAccount = new Set<String>();
		Map<String, String> jsonInputData = new Map<String, String>{ '#NUM_CLIENTE_PK' => '12560002' };
		try {
			Integration_Service.ServiceResponse response = Integration_Service.calloutService(
				'solicitarCliente',
				null,
				null,
				jsonInputData,
				true
			);
			Map<String, List<SObject>> sObjectMap = F3_JsonToSobject_Service.jsonToSobject(
				(String) response.serviceResponse,
				'crearActualizarCliente'
			);
			if (!sObjectMap.get('Account').isEmpty() && String.valueOf(response.serviceCode).startsWithIgnoreCase('2')) {
				Schema.SObjectField accExternalField = Account.Client_ID__c.getDescribe().getSObjectField();
				List<Database.upsertResult> upsertResults = Database.upsert(sObjectMap.get('Account'), accExternalField, false);
				if (!upsertResults.isEmpty()) {
					for (Database.upsertResult result : upsertResults) {
						if (result.isSuccess() == true) {
							insertedAccount.add(result.getId());
						}
					}
				}
				return String.join(new List<String>(insertedAccount), ',');
			} else {
				throw new F3_RestServices_Exception('Error ' + response.serviceCode + ' en el servicio: ' + response.serviceResponse);
			}
		} catch (Exception e) {
			throw new F3_RestServices_Exception(e.getMessage());
		}
	}

	public static String getPortfolio(String contractNumber, String executiveID) {
		Map<String, Object> parameters = new Map<String, Object>{ 'contractNumber' => contractNumber, 'promoterNumber' => executiveID };
		try {
			System.debug(System.Limits.getHeapSize());
			Integration_Service.ServiceResponse response = Integration_Service.calloutService(
				'PortafolioContrato',
				null,
				null,
				parameters,
				true
			);
			System.debug(System.Limits.getHeapSize());
			response.serviceHeaders = null;
			response.logger = null;
			return JSON.serialize(response);
		} catch (Exception e) {
			throw new F3_RestServices_Exception(e.getMessage());
		}
	}

	public static String getContractList(String startDate, String endDate, String currentUserId) {
		List<User> currentUser = [SELECT ID_ASESOR__c FROM USER WHERE Id = :currentUserId LIMIT 1];
		Map<String, Object> parameters = new Map<String, Object>{
			'startDate' => startDate,
			'endDate' => endDate,
			'currentUserId' => currentUser[0].ID_ASESOR__c
		};
		try {
			Integration_Service.ServiceResponse response = Integration_Service.calloutService(
				'VistaContrato',
				null,
				null,
				parameters,
				true
			);
			response.serviceHeaders = null;
			response.logger = null;
			return JSON.serialize(response);
		} catch (Exception e) {
			throw new F3_RestServices_Exception(e.getMessage());
		}
	}
	public static Lead fieldUpdateLead(Integration_Service.ServiceResponse response,Map<String, Object> leadMap, Boolean fieldsCompleted){
		Lead leadToUpdate = new Lead();
		leadToUpdate.Id =  (String) leadMap.get('Id');
		leadToUpdate.F3_Se_completaron_campos_minimos__c = fieldsCompleted;
		if (String.valueOf(response.serviceCode).startsWithIgnoreCase('2')) {
			leadToUpdate.Status = 'Formalización y Validación';
			leadToUpdate.F3_isCreatedInSAP__c = true;
		}
		return leadToUpdate;
	}

}