temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EstatusContacto__c</fullName>
        <label>Etapa contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contacto efectivo exitoso</fullName>
                </value>
                <value>
                    <fullName>Contacto no exitoso</fullName>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cliente no quiere ser contactado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Identificador Cliente</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/F3_CURP__c.field-meta.xml
<CustomField>
    <fullName>F3_CURP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CURP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo de Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

temp/audit/qa/unpackaged/objects/ResumenGlobalPostventa__c.object
<CustomObject>
    <fields>
        <fullName>Banker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Banquero</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Resumenes globales postventa</relationshipLabel>
        <relationshipName>Resumenes_globales_postventa</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contactados__c</fullName>
        <label>Contactados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalId_Nomina__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ExternalId Nomina</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fecha</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meta__c</fullName>
        <label>Meta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Resumen global postventa</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resumen</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumenes globales postventa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PSTA_RegistroResumenGlobal_cls_Test.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Gallegos Alan
* Project           :   Post venta
* Clase test		:   
* Description       :   Clase test para el Batch de reseteo de estatus de contacto
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         28-Jul-2025       Gallegos Alan          Creación
*--------------------------------------------------------------------------
*******************************************************************************/
@IsTest
public class PSTA_RegistroResumenGlobal_cls_Test {


private static User createTestUser() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name IN ('System Administrator', 'Administrador del sistema') LIMIT 1];
        User user = new User(
            LastName = 'User1',
            Username = 'user1_' + System.currentTimeMillis() + '@test.com',
            Email = 'user1@test.com',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = 'usr1',
            IsActive = true,
            TimeZoneSidKey = 'America/Mexico_City',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'es',
            ID_ASESOR__c = '0001',
            ProfileId = adminProfile.Id
        );
        insert user;
        return user;
    }


    private static Account createTestAccount(User user, Id bankerMemberId) {
        Account account = new Account(
            FirstName = 'TestName',
            MiddleName = 'TestMiddle',
            LastName = 'TestApp',
            F3_CURP__c = 'TESTING1',
            Client_ID__c = '02030',
            ID_Asesor__c = '0001',
            SaldoIntegral__c = 123,
            BanqueroAsignado__c = bankerMemberId,
            Person_Type__c = 'Persona Fisica',
            FechaSiguienteContacto__c = Date.today(),
            EstatusContacto__c = 'Contacto no exitoso',
            OwnerId = [SELECT Id FROM User WHERE Name = 'IntegrationUser' LIMIT 1].Id,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId()
        );
        
        OD_Account_cls.bypassTriggerExecution = true;
        PSTA_ListadoClientes_cls.bypassTriggerExecution = true;
        PSTA_Segmentacion_cls.bypassTriggerExecution = true;

        insert account;
        return account;
    }

     private static BranchUnit createTestBranchUnit() {
        BranchUnit branchUnit = new BranchUnit(
            Name = 'TestBranchUnit',
            IsActive = true,
            BranchCode = '10000012345',
            ExternalIdBI__c = '37',
            ExternalId__c = '10000012345'
        );
        insert branchUnit;
        return branchUnit;
    }

    private static Id createBankerMembership(User user, BranchUnit branchUnit) {
        Banker banker = new Banker(
            Name = 'TestBankerContact',
            JobCode = '0001',
            CurrentBranchId = branchUnit.Id,
            UserOrContactId = user.Id
        );
        insert banker;

        List<BranchUnitBusinessMember> existing = [
            SELECT Id FROM BranchUnitBusinessMember
            WHERE BranchUnitId = :branchUnit.Id
            AND BusinessUnitMemberId = :banker.Id
        ];
        return existing[0].Id;
    }


    private static void createContactWithoutLicense() {
        Contact c = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('BanqueroLlicencia').getRecordTypeId(),
            FirstName = 'TestName',
            LastName = 'TestApp',
            EmpleadoSinLicenciaSFDC__c = true,
            NumeroNomina__c = '0001'
        );
        insert c;
    }

    private static void createResumen() {
        ResumenGlobalPostventa__c resAux = new ResumenGlobalPostventa__c(
                Name = 'Resumen Test',
                Fecha__c = System.today(),              
                OwnerId = [SELECT Id FROM User WHERE Name = 'IntegrationUser' LIMIT 1].Id,
                Banker__c = [SELECT Id FROM BranchUnitBusinessMember LIMIT 1].Id,
                ExternalId_Nomina__c = '123456789',
                Contactados__c = 0,
                Meta__c = 10
        );
        insert resAux;
    }

     @isTest 
    static void testGetResumenesActuales() {
        User user = createTestUser();
        BranchUnit branchUnit = createTestBranchUnit();
        Id bankerMemberId = createBankerMembership(user, branchUnit);
        createContactWithoutLicense();
        PSTA_TestDataFactory.createConfiguracionContactoActinver();
        PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        createTestAccount(user, bankerMemberId);

        Test.startTest();
        PSTA_RegistroResumenGlobal_cls.getResumenesActuales();
        Test.stopTest();

        System.assert(true, 'Clase test terminada.');
    }


    @isTest 
    static void testGetAllDivisions() {
        PSTA_TestDataFactory.createConfiguracionContactoActinver();
        PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        User user = createTestUser();
        BranchUnit branchUnit = createTestBranchUnit();
        Id bankerMemberId = createBankerMembership(user, branchUnit);
        createContactWithoutLicense();
        createTestAccount(user, bankerMemberId);


        Test.startTest();
        PSTA_RegistroResumenGlobal_cls.getAllDivisions();
        Test.stopTest();

        System.assert(true, 'Clase test terminada.');
    }


    @isTest 
    static void testGetUserIds() {
        PSTA_TestDataFactory.createConfiguracionContactoActinver();
        PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        User user = createTestUser();
        BranchUnit branchUnit = createTestBranchUnit();
        Id bankerMemberId = createBankerMembership(user, branchUnit);
        createContactWithoutLicense();
        createTestAccount(user, bankerMemberId);

        Test.startTest();
        PSTA_RegistroResumenGlobal_cls.getUserIds();
        Test.stopTest();

        System.assert(true, 'Clase test terminada.');
    }


    @isTest 
    static void testUpdateRecords() {
        PSTA_TestDataFactory.createConfiguracionContactoActinver();
        PSTA_TestDataFactory.createConfiguracionPatrimonialReactivoActinver();
        User user = createTestUser();
        BranchUnit branchUnit = createTestBranchUnit();
        Id bankerMemberId = createBankerMembership(user, branchUnit);
        createContactWithoutLicense();
        createTestAccount(user, bankerMemberId);
        createResumen();

        // List<ResumenGlobalPostventa__c> testList = [SELECT Id, Name FROM ResumenGlobalPostventa__c LIMIT 1];
        List<ResumenGlobalPostventa__c> testList = new List<ResumenGlobalPostventa__c>();
        Map<Id,ResumenGlobalPostventa__c> testMap = new Map<Id,ResumenGlobalPostventa__c>();

        ResumenGlobalPostventa__c newTest = new ResumenGlobalPostventa__c(
            Id = [SELECT Id, Name, Banker__c, CreatedDate FROM ResumenGlobalPostventa__c LIMIT 1].Id,
            Banker__c = [SELECT Id FROM Banker LIMIT 1].Id
        );

        testList.add(newTest);
        testMap.put(newTest.Id, testList[0]);

        Test.startTest();
        PSTA_RegistroResumenGlobal_cls.upsertRecords(testList);
        Test.stopTest();

        System.assert(true, 'Clase test terminada.');
    }



}