temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactoPriorizadoEsteMes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacto priorizado este mes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_Asesor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Conqueempresaestasasegurado__c.field-meta.xml
<CustomField>
    <fullName>Conqueempresaestasasegurado__c</fullName>
    <label>¿Con qué empresa estas asegurado?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actinver</fullName>
            </value>
            <value>
                <fullName>Quálitas Seguro</fullName>
            </value>
            <value>
                <fullName>Grupo Nacional Provincial (GNP)</fullName>
            </value>
            <value>
                <fullName>Chubb Seguros</fullName>
            </value>
            <value>
                <fullName>BBVA Seguros</fullName>
            </value>
            <value>
                <fullName>Axa Seguros</fullName>
            </value>
            <value>
                <fullName>HDI Seguros</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>MapfreSeguros Banorte</fullName>
            </value>
            <value>
                <fullName>MapfreSeguros Afirme</fullName>
            </value>
            <value>
                <fullName>MapfreSeguros Inbursa</fullName>
            </value>
            <value>
                <fullName>MapfreMetLife</fullName>
            </value>
            <value>
                <fullName>MapfreSeguros Argos</fullName>
            </value>
            <value>
                <fullName>MapfreZurich Santander</fullName>
            </value>
            <value>
                <fullName>MapfreSeguros Citibanamex</fullName>
            </value>
            <value>
                <fullName>MapfreHSBC Seguros</fullName>
            </value>
            <value>
                <fullName>Seguros Monterrey New York Life</fullName>
            </value>
            <value>
                <fullName>Deco Seguros</fullName>
            </value>
            <value>
                <fullName>Prudential</fullName>
            </value>
            <value>
                <fullName>Zurich Aseguradora Mexicana</fullName>
            </value>
            <value>
                <fullName>Solunion México</fullName>
            </value>
            <value>
                <fullName>Tokio Marine Compañía de Seguros</fullName>
            </value>
            <value>
                <fullName>Seguros Atlas</fullName>
            </value>
            <value>
                <fullName>Allianz México</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Conquetipodeseguroscuentas__c.field-meta.xml
<CustomField>
    <fullName>Conquetipodeseguroscuentas__c</fullName>
    <label>¿Con qué tipo de seguros cuentas?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro de Auto</fullName>
            </value>
            <value>
                <fullName>Seguro de Gastos Médicos Mayores</fullName>
            </value>
            <value>
                <fullName>Seguro de Vida</fullName>
            </value>
            <value>
                <fullName>Seguro de Hogar</fullName>
            </value>
            <value>
                <fullName>Seguro de Accidentes Personales</fullName>
            </value>
            <value>
                <fullName>Seguro Educativo</fullName>
            </value>
            <value>
                <fullName>Seguro Mascotas</fullName>
            </value>
            <value>
                <fullName>Seguros de Ahorro o Inversión (Dotal)</fullName>
            </value>
            <value>
                <fullName>Seguro de Viaje</fullName>
            </value>
            <value>
                <fullName>Seguro de Bicicleta</fullName>
            </value>
            <value>
                <fullName>Seguro de Vida e inversión</fullName>
            </value>
            <value>
                <fullName>No aplica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CuandoVence__c.field-meta.xml
<CustomField>
    <fullName>CuandoVence__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>¿Cuándo vence?</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cuantos_hijos_tienes__c.field-meta.xml
<CustomField>
    <fullName>Cuantos_hijos_tienes__c</fullName>
    <label>¿Cuántos hijos tienes?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>No aplica</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FamiliarqueseaclienteenActinver__c.field-meta.xml
<CustomField>
    <fullName>FamiliarqueseaclienteenActinver__c</fullName>
    <label>¿Familiar que sea cliente en Actinver?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FechaSiguienteContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaSiguienteContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha siguiente contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Frecuencia_para_ser_contactado__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_para_ser_contactado__c</fullName>
    <label>Frecuencia para ser contactado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cada mes</fullName>
            </value>
            <value>
                <fullName>Cada dos meses</fullName>
            </value>
            <value>
                <fullName>Cada tres meses</fullName>
            </value>
            <value>
                <fullName>Cada cuatro meses</fullName>
            </value>
            <value>
                <fullName>Cada seis meses</fullName>
            </value>
            <value>
                <fullName>Una vez al año</fullName>
            </value>
            <value>
                <fullName>El cliente prefiere contactarse con nosotros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InstitucionFinancieraPrincipal__c.field-meta.xml
<CustomField>
    <fullName>InstitucionFinancieraPrincipal__c</fullName>
    <inlineHelpText>Institución donde manejas la mayoria de tus activos, productos financieros o realizas la mayoría de tus transacciones.</inlineHelpText>
    <label>Institución financiera principal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBVA</fullName>
            </value>
            <value>
                <fullName>Citi</fullName>
            </value>
            <value>
                <fullName>Banamex</fullName>
            </value>
            <value>
                <fullName>Santander</fullName>
            </value>
            <value>
                <fullName>Scotiabank</fullName>
            </value>
            <value>
                <fullName>Inbursa</fullName>
            </value>
            <value>
                <fullName>Banorte</fullName>
            </value>
            <value>
                <fullName>HSBC</fullName>
            </value>
            <value>
                <fullName>GBM</fullName>
            </value>
            <value>
                <fullName>Invex</fullName>
            </value>
            <value>
                <fullName>Mifel</fullName>
            </value>
            <value>
                <fullName>Actinver</fullName>
            </value>
            <value>
                <fullName>Monex</fullName>
            </value>
            <value>
                <fullName>Masari</fullName>
            </value>
            <value>
                <fullName>BanRegio</fullName>
            </value>
            <value>
                <fullName>Multiva</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MedioPreferidoContacto__c.field-meta.xml
<CustomField>
    <fullName>MedioPreferidoContacto__c</fullName>
    <label>Medio preferido de contacto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Llamada telefónica</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Visita</fullName>
            </value>
            <value>
                <fullName>Videollamada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MesPreferenteInversion_o_ahorrar__c.field-meta.xml
<CustomField>
    <fullName>MesPreferenteInversion_o_ahorrar__c</fullName>
    <label>Mes preferente para invertir / ahorrar</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enero</fullName>
            </value>
            <value>
                <fullName>Febrero</fullName>
            </value>
            <value>
                <fullName>Marzo</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Mayo</fullName>
            </value>
            <value>
                <fullName>Junio</fullName>
            </value>
            <value>
                <fullName>Julio</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Septiembre</fullName>
            </value>
            <value>
                <fullName>Octubre</fullName>
            </value>
            <value>
                <fullName>Noviembre</fullName>
            </value>
            <value>
                <fullName>Diciembre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo de Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PorqueIndentInteres__c.field-meta.xml
<CustomField>
    <fullName>PorqueIndentInteres__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>¿Por qué es tu principal?</inlineHelpText>
    <label>¿Por qué?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Patrimonial</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Patrimonial reactivo</fullName>
            </value>
            <value>
                <fullName>Institucional</fullName>
            </value>
            <value>
                <fullName>Gobierno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Viajas_recurrentemente__c.field-meta.xml
<CustomField>
    <fullName>Viajas_recurrentemente__c</fullName>
    <label>¿Viajas recurrentemente?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Privada.recordType-meta.xml
<RecordType>
    <fullName>Privada</fullName>
    <active>true</active>
    <description>Tipo de registro para las cuentas de tipo Privada</description>
    <label>Privada</label>
</RecordType>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BanqueroAsignado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banquero Asignado</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ID_ASESOR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Asesor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSTA_TestDataFactory.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Canche Isaac
* Project           :   Post Venta
* Description       :   Clase helper que crea registros para pruebas de postventa
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         23-Jul-2025       Canche Isaac              Creación
*--------------------------------------------------------------------------
*******************************************************************************/

public class PSTA_TestDataFactory {
    public static final Id idConfigContactoPostVentaRecordType = Schema.SObjectType.ConfiguracionActinver__c.getRecordTypeInfosByDeveloperName().get('ContactoPostventa').getRecordTypeId();
    public static final Id idConfigContratosPostVentaRecordType = Schema.SObjectType.ConfiguracionActinver__c.getRecordTypeInfosByDeveloperName().get('PSTA_ConfiguracionContratosPostventa').getRecordTypeId();
    // Método para crear configuración personalizada
    public static ConfiguracionActinver__c createConfiguracionContratosActinver() {
        ConfiguracionActinver__c config = new ConfiguracionActinver__c(
            Name = 'Configuración Test',
            TipoContratos__c = '01;02',
            EstatusContrato__c = 'Nuevo',
            RecordTypeId = idConfigContratosPostVentaRecordType
        );
        insert config;
        return config;
    }
    public static ConfiguracionActinver__c createConfiguracionContactoActinver() {
        ConfiguracionActinver__c config = new ConfiguracionActinver__c(
            Name = 'Configuración privada',
            Segmento__c ='Privada',
            RangoMontoMaximo__c = 20000,
            RangoMontoMinimo__c = 0,
            FrecuenciaContacto__c = 20,
            FrecuenciaVisita__c = 120,
            FrecReinicioNoReqContacto__c = '120',
            ClientesContactarPorDia__c = 5,
            RecordTypeId = idConfigContactoPostVentaRecordType
        );
        insert config;
        return config;
    }

    public static ConfiguracionActinver__c createConfiguracionPatrimonialReactivoActinver() {
        ConfiguracionActinver__c config = new ConfiguracionActinver__c(
            Name = 'Configuración patrimonial reactivo',
            Segmento__c ='Patrimonial reactivo',
            Rol__c = 'Farmer',
            RangoMontoMaximo__c = 200000,
            RangoMontoMinimo__c = 0,
            FrecuenciaContacto__c = 20,
            FrecuenciaVisita__c = 120,
            FrecReinicioNoReqContacto__c = '120',
            ClientesContactarPorDia__c = 5,
            RecordTypeId = idConfigContactoPostVentaRecordType
        );
        insert config;
        return config;
    }

    public static User createUser(){
        String adminProfileId = [SELECT Id FROM Profile WHERE name IN ('System Administrator', 'Administrador del sistema')].Id;
        User user = new User();
        user.LastName = 'User1';
        user.Username = 'User1@user.com.u';
        user.Email = 'Useruser@u.com.u';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.Alias = 'uAas2';
        user.IsActive = true;
        user.TimeZoneSidKey = 'America/Mexico_City';
        user.LocaleSidKey = 'en_US';
        user.LanguageLocaleKey = 'es';
        user.ID_ASESOR__c = '00045';
        user.ProfileId = adminProfileId;
        insert user;
        return user;
    }


    public static BranchUnit createBranchUnit(){
        BranchUnit branchUnit = new BranchUnit();
        branchUnit.Name = 'Test';
        branchUnit.IsActive = true;
        branchUnit.BranchCode = '10000012345';
        branchUnit.ExternalIdBI__c = '37';
        branchUnit.ExternalId__c = '10000012345';
        insert branchUnit;
        return branchUnit;
    }

    public static Banker createBanker(Id branchUnitId, Id userId){
        Banker bankerContact = new Banker();
        bankerContact.Name = 'TestBankerContact1';
        bankerContact.JobCode = '00045';
        bankerContact.ExternalId__c = '00045';
        bankerContact.Division__c = 'Privada';
        bankerContact.CurrentBranchId = branchUnitId;
        bankerContact.UserOrContactId = userId;
        insert bankerContact;
        return bankerContact;
    }


    public static BranchUnitBusinessMember getBranchUnitBusinessMember(Id idBanker, Id idBranchUnit){
        return [SELECT Id, ExternalId__c FROM BranchUnitBusinessMember WHERE BranchUnitId =: idBranchUnit AND BusinessUnitMemberId =: idBanker AND IsActive = true LIMIT 1];
    }
    
    

    // Método para crear cuentas
    public static List<Account> createAccounts(Integer numCuentas,Id idBanquero, Boolean doInsert) {
        List<Account> cuentas = new List<Account>();
        for(Integer i = 0; i < numCuentas; i++) {
            cuentas.add(new Account(
                Name = 'Cuenta Test ' + i,
                InstitucionFinancieraPrincipal__c = 'Banorte',
                PorqueIndentInteres__c = 'Prueba',
                Conquetipodeseguroscuentas__c = 'Seguro de Auto',
                CuandoVence__c = System.today(),
                Conqueempresaestasasegurado__c = 'Mapfre',
                MesPreferenteInversion_o_ahorrar__c = 'Febrero',
                Cuantos_hijos_tienes__c = '1',
                Viajas_recurrentemente__c = 'No',
                FamiliarqueseaclienteenActinver__c = 'No',
                Frecuencia_para_ser_contactado__c = 'El cliente prefiere contactarse con nosotros',
                MedioPreferidoContacto__c = 'Mail',
                BanqueroAsignado__c = idBanquero,
                Person_Type__c = 'FISICA',
                ID_Asesor__c = '00045'
            ));
        }
        if(doInsert) {
            OD_Account_cls.bypassTriggerExecution = true;
            insert cuentas;
        }
        return cuentas;
    }

    // Método para crear cuentas
    public static List<Account> createAccountsPriorizacion(Integer numCuentas,Id idBanquero, Boolean doInsert) {
        List<Account> cuentas = new List<Account>();
        for(Integer i = 0; i < numCuentas; i++) {
            cuentas.add(new Account(
                Name = 'Cuenta Test ' + i,
                InstitucionFinancieraPrincipal__c = 'Banorte',
                PorqueIndentInteres__c = 'Prueba',
                Conquetipodeseguroscuentas__c = 'Seguro de Auto',
                CuandoVence__c = System.today(),
                Conqueempresaestasasegurado__c = 'Mapfre',
                MesPreferenteInversion_o_ahorrar__c = 'Febrero',
                Cuantos_hijos_tienes__c = '1',
                Viajas_recurrentemente__c = 'No',
                FamiliarqueseaclienteenActinver__c = 'No',
                Frecuencia_para_ser_contactado__c = 'El cliente prefiere contactarse con nosotros',
                MedioPreferidoContacto__c = 'Mail',
                BanqueroAsignado__c = idBanquero,
                Segmento__c = 'Privada',
                FechaSiguienteContacto__c = System.today().addDays(-i * 10),
                ContactoPriorizadoEsteMes__c = true
            ));
        }
        if(doInsert) {
            OD_Account_cls.bypassTriggerExecution = true;
            insert cuentas;
        }
        return cuentas;
    }

    // Método para crear contratos
    public static List<Contract> createContracts(List<Id> accountIds, String idAsesor, Boolean doInsert,Id banqueroAsignado) {
        List<Contract> contratos = new List<Contract>();
        List<String> tiposContrato = new List<String>{'01', '02', '03'};
        List<String> estatus = new List<String>{'Aprobado', 'En proceso de validación', 'Cancelado'};
        for(Integer i = 0; i < accountIds.size(); i++) {
            Integer daysAgo = (i + 1) * 30;
            contratos.add(new Contract(
                AccountId = accountIds[i],
                TypeOfContract__c = '01',
                Status__c = 'Nuevo',
                AccountOpeningDate__c = Date.today().addDays(-daysAgo),
                Saldo__c = ''+i+1+'00',
                ID_ASESOR__c = idAsesor,
                BanqueroAsignado__c = banqueroAsignado
            ));
        }
        
        if(doInsert) {
            OD_Contract_cls.bypassTriggerExecution = true;
            insert contratos;
        }
        return contratos;
    }

}