temp/audit/fullcopy/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/BanqueroAsignado__c.field-meta.xml
<CustomField>
    <fullName>BanqueroAsignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquero Asignado</label>
    <referenceTo>BranchUnitBusinessMember</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnrolamientoActivo__c.field-meta.xml
<CustomField>
    <fullName>EnrolamientoActivo__c</fullName>
    <label>Usuario BE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>No Activo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnrolamientoBiometricos__c.field-meta.xml
<CustomField>
    <fullName>EnrolamientoBiometricos__c</fullName>
    <label>Enrolamiento Biométricos</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Enrolado</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>No enrolado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FechaUltimoContacto__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimoContacto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha último contacto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FichaAfinidadCompletada__c.field-meta.xml
<CustomField>
    <fullName>FichaAfinidadCompletada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ficha de afinidad completada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SaldoIntegral__c.field-meta.xml
<CustomField>
    <fullName>SaldoIntegral__c</fullName>
    <description>Representa la suma del saldo de los contratos que actualmente tiene la cuenta. Este campo se llena mediante un proceso batch. Adicional, los criterios para la selección de los contratos son definidos por negocio</description>
    <label>Saldo integral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

temp/audit/qa/unpackaged/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BanqueroAsignado__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banquero Asignado</label>
        <referenceTo>BranchUnitBusinessMember</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FLAG_EVENTS_INVITATIONS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Invitación Eventos</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLAG_MARKETING_ACTINVER__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Publicidad Actinver</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLAG_MARKETING__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mercadeo</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlaneacionFinancieraCompletada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planeación financiera completada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PropuestaInversionCompletada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Propuesta de inversión completada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En proceso de validación</fullName>
                </value>
                <value>
                    <fullName>C01</fullName>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>C02</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>C03</fullName>
                    <label>Cerrado</label>
                </value>
                <value>
                    <fullName>C05</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>C06</fullName>
                    <label>Bloqueado</label>
                </value>
                <value>
                    <fullName>CC01</fullName>
                    <label>Nuevo.</label>
                </value>
                <value>
                    <fullName>CC02</fullName>
                    <label>Cancelado.</label>
                </value>
                <value>
                    <fullName>CC05</fullName>
                    <label>Aprobado.</label>
                </value>
                <value>
                    <fullName>CC06</fullName>
                    <label>Bloqueado.</label>
                </value>
                <value>
                    <fullName>CC07</fullName>
                    <label>Registrado Bursanet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeOfContract__c</fullName>
        <label>Tipo de contrato</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UN PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UNA CUENTA PERSONAL PARA EL AHORRO</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>CONTRATO MARCO DE COMPRAVENTA DE DIVISAS (BANCO)</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA ACTINVER)</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA DE NÓMINA ACTINVER)</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>TRADICIONAL DE INTERMEDIACIÓN BURSÁTIL</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>PLAN PERSONAL DE RETIRO</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>CONTRATO CUENTA LÍQUIDA ACTINVER</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Bursanet</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>Bursanet.</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Bursanet,</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>DINN</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Banco Persona Moral</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Banco Persona  Moral</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Banco  Persona Moral</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PV_GenerarTareasPeriodicasSelector_cls.cls
/******************************************************************************* 
* Developed by      :   VASS México
* Author            :   Martín Martínez
* Project           :   Post venta
* Clase test		:   
* Description       :   Clase selector que contiene todas las SOQL o DML del batch para crear nuevas tareas por periodicidad.
*--------------------------------------------------------------------------
* No.            Date              Author                Description
* 1.0         19-Jun-2025       Martín Martínez              Creación
*--------------------------------------------------------------------------
*******************************************************************************/
public with sharing class PV_GenerarTareasPeriodicasSelector_cls {

    public static final Id idConfigPostVentaRecordType = Schema.SObjectType.ConfiguracionActinver__c.getRecordTypeInfosByDeveloperName().get('ConfiguracionPeriodicidadTareas').getRecordTypeId();

    public static String getQueryAccounts(){
        String consulta = [SELECT Consulta__c FROM PSTA_Consultas__mdt WHERE DeveloperName = 'PSTA_Query_Generar_Tareas'].Consulta__c ;
        return consulta;
        
            
    }

    /* public static String getQueryAccounts(){
        return 'SELECT Id, Name,' +
                    'FechaUltimoContacto__c, ' +
                    'EnrolamientoBiometricos__c, ' +
                    'EnrolamientoActivo__c, ' +
                    'FichaAfinidadCompletada__c, ' +
                    'PersonContactId, ' +
                    'BanqueroAsignado__r.BusinessUnitMemberId ' +
                'FROM Account ' +
                'WHERE CreatedDate = TODAY' +//Id IN (\'001dz0000078XvfAAE\', \'001dz000006wr5JAAQ\', \'001dz000007BDsMAAW\') ';
                ' AND SaldoIntegral__c != null AND IsPersonAccount = TRUE AND BanqueroAsignado__c != null';
    } */

    public static List<ActionCadence> getCadence() {
        return [SELECT Id,
                    Name,
                    Tipo_de_actividad__c,
                    Periodicidad__c,
                    DeveloperName__c,
                    TareaUnicaPorContrato__c, 
                    TareaUnicaPorCuenta__c
                FROM ActionCadence
                WHERE State ='Active'];
    }   

    public static List<Contract> getContratosClienteNoContactar(Set<Id> accountIds) {
        return [SELECT AccountId, FLAG_MARKETING__c, FLAG_MARKETING_ACTINVER__c, FLAG_EVENTS_INVITATIONS__c
                FROM Contract
                WHERE AccountId IN :accountIds
                AND (FLAG_MARKETING__c != null 
                    AND FLAG_MARKETING_ACTINVER__c != null 
                    AND FLAG_EVENTS_INVITATIONS__c != null)
            ];
    } 

    public static Set<Id> getAccountsWithValidContracts(Set<Id> accountIds, Set<String> validContractTypes, Set<String> validContractStatuses) {
        Set<Id> validAccountIds = new Set<Id>();
        if (accountIds == null || accountIds.isEmpty() || validContractTypes == null || validContractTypes.isEmpty() ||
            validContractStatuses == null || validContractStatuses.isEmpty()) {
            return validAccountIds;
        }

        for (AggregateResult result : [
            SELECT AccountId accountId
            FROM Contract
            WHERE AccountId IN :accountIds
                AND TypeOfContract__c IN :validContractTypes
                AND Status__c IN :validContractStatuses
            GROUP BY AccountId
        ]) {
            validAccountIds.add((Id) result.get('accountId'));
        }

        return validAccountIds;
    }

    public static List<Banker> getBankerByBusinessMemberId(Set<Id> setBMemberId){
        return [SELECT ID, UserOrContactId, ExternalId__c FROM BANKER WHERE ID IN: setBMemberId];
    }

    public static Id getDiasLaborales(){
        return [SELECT Id FROM BusinessHours WHERE Name = 'Postventa'].Id;
    }

    public static List<ActionCadenceTracker> validateCadenceActive(Set<Id> accountIds, String developerNameCadencia, Boolean cadenciaUnicaPorCuenta) {
        String baseQuery = 'SELECT ActionCadence.DeveloperName__c, TargetId ' +
                        'FROM ActionCadenceTracker ' +
                        'WHERE ActionCadence.DeveloperName__c = :developerNameCadencia ';

        /*Boolean esCadenciaEspecial = 
            developerNameCadencia == PSTA_UtilityClass.DEVELOPERNAME_BIOMETRICOS || 
            developerNameCadencia == PSTA_UtilityClass.DEVELOPERNAME_BANCA_ELECTRONICA;

        if (!esCadenciaEspecial || !cadenciaUnicaPorCuenta) {*/
            baseQuery += 'AND State = \'Running\' ';
        //}


        baseQuery += 'AND TargetId IN :accountIds';

        return Database.query(baseQuery);
    }

    public static List<Contract> getContratosNoPropuestaPlaneacion(Set<Id> accountIds) {
        return [
            SELECT Id, AccountId, Account.PersonContactId, PlaneacionFinancieraCompletada__c, PropuestaInversionCompletada__c
            FROM Contract
            WHERE AccountId IN :accountIds
            AND (PlaneacionFinancieraCompletada__c = false
            OR PropuestaInversionCompletada__c = false)
        ];
    }

    public static List<Task> getTask(Set<Id> accountIds, String developerNameCadencia) {
        Integer mesesFiltro;
        try {
            mesesFiltro = Integer.valueOf(Label.MesesFiltroTareas);
        } catch(Exception e) {
            mesesFiltro = 6;
        }

        Date fechaLimite = Date.today().addMonths(-mesesFiltro);
        return [
            SELECT AccountId, CreatedDate, DeveloperName__c
            FROM Task
            WHERE DeveloperName__c = :developerNameCadencia
              AND AccountId IN :accountIds
              AND DeveloperName__c != null
              AND CreatedDate >= :fechaLimite
            ORDER BY AccountId, CreatedDate DESC
        ];
    }

}