docs/rollback/actipm-opportunity-listviews/deployed/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Error_escalationProcess_MKT__c.field-meta.xml
<CustomField>
    <fullName>Error_escalationProcess_MKT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Errores Escalaciones</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_From_MKT_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Is_From_MKT_Calculator__c</fullName>
    <formula>AND(
 CASESAFEID(CreatedById)  =  &quot;0055e000005hqg7AAA&quot;,
 NOT(CASESAFEID(Account.OwnerId) = &quot;0055e0000078BbjAAE&quot;),
 OR( 
    RecordType.DeveloperName  =  &quot;Planes_Beneficio_Fiscal&quot;,
    RecordType.DeveloperName  =  &quot;WalletShareOpportunity&quot;
 ) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculadora MKT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EscalationOpportunity_Scheduler.cls
global without sharing class EscalationOpportunity_Scheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        String OPP_VALID_STAGES = '\'Identificar Necesidades\','+ '\'Presentación de oferta\'';
            
        String query = 'SELECT '+ Label.CalculateBusinessHoursFields + 
        ' FROM Opportunity' +
        ' WHERE Is_From_MKT_Calculator__c = true' +
		' AND IsClosed = false' +
        ' AND Error_escalationProcess_MKT__c = null' +
        ' AND StageName IN('+ OPP_VALID_STAGES + ')';

        Database.executeBatch(new EscalationCalculateBusinessHours_Batch(query), 100);
    }
}