temp/onboarding_retrieve/qa/objects/Lead/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Línea de acción</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads &amp; Referrals</relationshipLabel>
    <relationshipName>Leads_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_Consecutivo_ID__c.field-meta.xml
<CustomField>
    <fullName>F3_Consecutivo_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Consecutivo ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/FinServ__ExpressedInterest__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ExpressedInterest__c</fullName>
    <label>Expressed Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinServ__ProductList</valueSetName>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/Inversion_Inicial__c.field-meta.xml
<CustomField>
    <fullName>Inversion_Inicial__c</fullName>
    <label>Inversion Inicial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Menos de $500,000</fullName>
            </value>
            <value>
                <fullName>Entre $500,000 y $1,500,000</fullName>
            </value>
            <value>
                <fullName>$500,000 o Más</fullName>
            </value>
            <value>
                <fullName>$10,000 a $100,000</fullName>
            </value>
            <value>
                <fullName>$100,000 a $250,000</fullName>
            </value>
            <value>
                <fullName>Menos de $5,999 USD</fullName>
            </value>
            <value>
                <fullName>Entre $6,000 a $84,999 USD</fullName>
            </value>
            <value>
                <fullName>Más de $85,000 USD</fullName>
            </value>
            <value>
                <fullName>Entre $10,000 y $20,000</fullName>
                <isActive>false</isActive>
                <label>Entre $10,000 y $20,000</label>
            </value>
            <value>
                <fullName>Entre $20,000 y $30,000</fullName>
                <isActive>false</isActive>
                <label>Entre $20,000 y $30,000</label>
            </value>
            <value>
                <fullName>Menos de $10,000</fullName>
                <isActive>false</isActive>
                <label>Menos de $10,000</label>
            </value>
            <value>
                <fullName>Mas de $1,500,000</fullName>
                <isActive>false</isActive>
                <label>Más de $1,500,000</label>
            </value>
            <value>
                <fullName>Más de $30,000</fullName>
                <isActive>false</isActive>
                <label>Más de $30,000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/Miembro_de_l_nea_de_acci_n__c.field-meta.xml
<CustomField>
    <fullName>Miembro_de_l_nea_de_acci_n__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relación del miembro de línea de acción</description>
    <label>Miembro de línea de acción</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Prospectos (Miembro de línea de acción)</relationshipLabel>
    <relationshipName>Prospectos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/F3_LeadDuplicateChecker_Service.cls
/**
 *   ------------------------------------------------------------------------------------------------
 * @Name     F3_LeadDuplicateChecker_Service
 * @Author   luis.felipe.ortiz@pwc.com
 * @Date     Created: 01/01/2023
 * ------------------------------------------------------------------------------------------------
 * @Description Class to retrieve the duplicates of a lead based on Actinver's duplicate rules
 * ------------------------------------------------------------------------------------------------
 * @Changes
 * 01/01/2023 luis.felipe.ortiz@pwc.com
 *             Class creation.
 * ------------------------------------------------------------------------------------------------
 **/
public without sharing class F3_LeadDuplicateChecker_Service {
	/** -----------------------------------------------------------------------------
	 * @Description retrieve the duplicates
	 *--------------------------------------------------------------------------------
	 * @author   luis.felipe.ortiz@pwc.com
	 * @date     31/01/2023
	 * @return   List<Lead>
	 * example	 getDuplicates(String currentLeadEmail, String currentLeadPhone, Id currentLeadId)
	 **/
	@AuraEnabled(cacheable=true)
	public static List<Lead> getDuplicates(String currentLeadEmail, String currentLeadPhone, Id currentLeadId) {
		try {
			List<Lead> duplicateLeads;
			if (String.isNotBlank(currentLeadEmail) && String.isNotBlank(currentLeadPhone)) {
				duplicateLeads = [
					SELECT
						Id,
						CreatedDate,
						Phone,
						MobilePhone,
						Email,
						Name,
						Campaign__c,
						Campaign__r.Name,
						LeadSource,
						FinServ__ExpressedInterest__c,
						Inversion_Inicial__c,
						OwnerId,
						Owner.Name,
						Status,
						Miembro_de_l_nea_de_acci_n__c,
						Miembro_de_l_nea_de_acci_n__r.Name,
						CreatedById,
						CreatedBy.Name,
						PostalCode,
						F3_Consecutivo_ID__c,
						RecordTypeId,
						RecordType.Name
					FROM Lead
					WHERE Phone = :currentLeadPhone AND Email = :currentLeadEmail AND Id != :currentLeadId
				];
			} else {
				duplicateLeads = new List<Lead>();
			}
			return duplicateLeads;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}