temp/onboarding_retrieve/dev/objects/Lead/fields/F3_Consecutivo_ID__c.field-meta.xml
<CustomField>
    <fullName>F3_Consecutivo_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Consecutivo ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/F3_No_Poliza_Seguros__c.field-meta.xml
<CustomField>
    <fullName>F3_No_Poliza_Seguros__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>No. de Póliza de Seguros</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/F3_RFC__c.field-meta.xml
<CustomField>
    <fullName>F3_RFC__c</fullName>
    <description>RFC  que se enviará para generar el BP</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/Poliza_de_Seguros_Creada__c.field-meta.xml
<CustomField>
    <fullName>Poliza_de_Seguros_Creada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Póliza de Seguros Creada?</label>
    <type>Checkbox</type>
</CustomField>

temp/onboarding_retrieve/dev/objects/Lead/fields/Productos_ofertados__c.field-meta.xml
<CustomField>
    <fullName>Productos_ofertados__c</fullName>
    <label>Productos ofertados</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unidad_de_Negocio__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FONDOS DE INVERSIÓN</fullName>
            </value>
            <value>
                <fullName>BE , TDD , CHEQUERA</fullName>
            </value>
            <value>
                <fullName>MERCADO DINERO , CAPITALES, DERIVADOS</fullName>
            </value>
            <value>
                <fullName>CAMBIOS</fullName>
            </value>
            <value>
                <fullName>CREDITO</fullName>
            </value>
            <value>
                <fullName>SEGURO</fullName>
            </value>
            <value>
                <fullName>FIDEICOMISO</fullName>
            </value>
            <value>
                <fullName>ARRENDAMIENTO</fullName>
            </value>
            <value>
                <fullName>PRODCUTOS EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Dotales</fullName>
            </value>
            <value>
                <fullName>GMM</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Seguro Viaje</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
            <value>
                <fullName>Seguro PyME</fullName>
            </value>
            <value>
                <fullName>Empresarial</fullName>
            </value>
            <value>
                <fullName>01</fullName>
                <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UN PLAN PERSONAL DE RETIRO</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UNA CUENTA PERSONAL PARA EL AHORRO</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>CONTRATO MARCO DE COMPRAVENTA DE DIVISAS (BANCO)</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA ACTINVER)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA DE NÓMINA ACTINVER)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>TRADICIONAL DE INTERMEDIACIÓN BURSÁTIL</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>PLAN PERSONAL DE RETIRO</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>CONTRATO CUENTA LÍQUIDA ACTINVER</label>
            </value>
            <value>
                <fullName>BLINDAJE PATRIMONIAL</fullName>
                <isActive>false</isActive>
                <label>Blindaje Patrimonial</label>
            </value>
            <value>
                <fullName>PREVICANCER</fullName>
                <isActive>false</isActive>
                <label>PREVICANCER</label>
            </value>
            <value>
                <fullName>PRODUCTOS EXTRANJERO</fullName>
                <isActive>false</isActive>
                <label>PRODUCTOS EXTRANJERO</label>
            </value>
            <value>
                <fullName>Plan personal de retiro</fullName>
                <isActive>false</isActive>
                <label>Plan Personal de Retiro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <businessProcess>PS%2FCB Lead Process</businessProcess>
    <label>Prospecto</label>
</RecordType>

temp/onboarding_retrieve/dev/objects/Lead/recordTypes/Seguros.recordType-meta.xml
<RecordType>
    <fullName>Seguros</fullName>
    <active>true</active>
    <businessProcess>FinServ__Lead Process</businessProcess>
    <label>Seguros</label>
</RecordType>

docs/rollback/actipm-opportunity-listviews/deployed/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Credito_Creado__c.field-meta.xml
<CustomField>
    <fullName>Credito_Creado__c</fullName>
    <label>¿Crédito Desembolsado?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_Consecutivo_ID__c.field-meta.xml
<CustomField>
    <fullName>F3_Consecutivo_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Consecutivo ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_Credito_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>F3_Credito_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crédito Relacionado</label>
    <referenceTo>Credito__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_No_Poliza_Seguros__c.field-meta.xml
<CustomField>
    <fullName>F3_No_Poliza_Seguros__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>No. de Póliza de Seguros</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/F3_RFC__c.field-meta.xml
<CustomField>
    <fullName>F3_RFC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Poliza_de_Seguros_Creada__c.field-meta.xml
<CustomField>
    <fullName>Poliza_de_Seguros_Creada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Póliza de Seguros Creada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Productos_ofertados__c.field-meta.xml
<CustomField>
    <fullName>Productos_ofertados__c</fullName>
    <label>Productos ofertados</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unidad_de_Negocio__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FONDOS DE INVERSION</fullName>
                <label>Fondos de Inversión</label>
            </value>
            <value>
                <fullName>BE , TDD , CHEQUERA</fullName>
                <label>BE , TDD , Chequera</label>
            </value>
            <value>
                <fullName>MERCADO DINERO , CAPITALES, DERIVADOS</fullName>
                <label>Mercado dinero, Capitales, Derivados</label>
            </value>
            <value>
                <fullName>CAMBIOS</fullName>
                <label>Cambios</label>
            </value>
            <value>
                <fullName>CREDITO</fullName>
                <label>Credito</label>
            </value>
            <value>
                <fullName>FIDEICOMISO</fullName>
                <label>Fideicomiso</label>
            </value>
            <value>
                <fullName>ARRENDAMIENTO</fullName>
                <label>Arrendamiento</label>
            </value>
            <value>
                <fullName>PRODCUTOS EXTRANJERO</fullName>
                <label>Productos extranjero</label>
            </value>
            <value>
                <fullName>Líneas Empresariales</fullName>
            </value>
            <value>
                <fullName>Inversión Inteligente</fullName>
            </value>
            <value>
                <fullName>Seguro_Viaje</fullName>
                <label>Seguro de Viaje</label>
            </value>
            <value>
                <fullName>Vida Pagos Limitados</fullName>
            </value>
            <value>
                <fullName>Plan de Ahorro Mixto</fullName>
            </value>
            <value>
                <fullName>Plan de Ahorro Educación</fullName>
            </value>
            <value>
                <fullName>Inversión Asesorada</fullName>
            </value>
            <value>
                <fullName>Banca Soluciones</fullName>
            </value>
            <value>
                <fullName>Fondo Digital</fullName>
            </value>
            <value>
                <fullName>Pagare Platino</fullName>
            </value>
            <value>
                <fullName>Global X</fullName>
            </value>
            <value>
                <fullName>Carteras modelo</fullName>
            </value>
            <value>
                <fullName>Inversion</fullName>
            </value>
            <value>
                <fullName>PPR</fullName>
                <label>Retiro</label>
            </value>
            <value>
                <fullName>Inversion inteligente</fullName>
            </value>
            <value>
                <fullName>CD Platinum</fullName>
            </value>
            <value>
                <fullName>Cuenta Básica</fullName>
            </value>
            <value>
                <fullName>Cuenta Básica de Nómina</fullName>
            </value>
            <value>
                <fullName>Portabilidad de Nómina</fullName>
            </value>
            <value>
                <fullName>Mercado de Derivados</fullName>
            </value>
            <value>
                <fullName>Mercado de Cambios</fullName>
            </value>
            <value>
                <fullName>Cuenta Personal Especial para el Ahorro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Financiamiento.recordType-meta.xml
<RecordType>
    <fullName>Financiamiento</fullName>
    <active>true</active>
    <businessProcess>FinServ__Wallet Share</businessProcess>
    <label>Financiamiento</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <businessProcess>Seguros</businessProcess>
    <label>Seguros</label>
</RecordType>

force-app/main/default/classes/F3_UnrelatedAccountChildren_Service.cls
/**
 *   ------------------------------------------------------------------------------------------------
 * @Name     F3_UnrelatedAccountChildren_Service
 * @Author   luis.felipe.ortiz@pwc.com
 * @Date     Created: 01/01/2023
 * ------------------------------------------------------------------------------------------------
 * @Description Class to get the unrelated opps and leads of the account
 * ------------------------------------------------------------------------------------------------
 * @Changes
 * 01/01/2023 luis.felipe.ortiz@pwc.com
 *             Class creation.
 * ------------------------------------------------------------------------------------------------
 **/
public with sharing class F3_UnrelatedAccountChildren_Service {
	/** -----------------------------------------------------------------------------
	 * @Description retrieve the open Financing and Insurance opps of the accounts
	 *--------------------------------------------------------------------------------
	 * @author   luis.felipe.ortiz@pwc.com
	 * @date     31/01/2023
	 * @return   List<Opportunity>
	 * example	getUnrelatedAccountOpps(List<Id> accountIds)
	 **/
	@AuraEnabled(cacheable=true)
	public static List<Opportunity> getUnrelatedAccountOpps(List<Id> accountIds) {
		return [
			SELECT
				Id,
				RecordType.Name,
				StageName,
				F3_Consecutivo_ID__c,
				OwnerId,
				Owner.Name,
				Name,
				F3_No_Poliza_Seguros__c,
				Poliza_de_Seguros_Creada__c,
				Credito_Creado__c,
				AccountId
			FROM Opportunity
			WHERE
				ContractId = NULL
				AND F3_Credito_Relacionado__c = NULL
				AND RecordType.Name IN ('Financiamiento', 'Seguros')
				AND StageName = 'Formalización y Validación'
				AND AccountId IN :accountIds
		];
	}

	/** -----------------------------------------------------------------------------
	 * @Description retrieve the probable insurance source leads of the account
	 *--------------------------------------------------------------------------------
	 * @author   luis.felipe.ortiz@pwc.com
	 * @date     31/01/2023
	 * @return   List<Opportunity>
	 * example	getUnrelatedAccountOpps(List<Id> accountIds)
	 **/
	@AuraEnabled(cacheable=true)
	public static List<Lead> getUnrelatedAccountLeads(String accountRFC) {
		return String.isBlank(accountRFC)
			? new List<Lead>()
			: [
					SELECT
						Id,
						RecordType.Name,
						Status,
						F3_Consecutivo_ID__c,
						OwnerId,
						Owner.Name,
						Name,
						Productos_ofertados__c,
						F3_No_Poliza_Seguros__c,
						Poliza_de_Seguros_Creada__c
					FROM Lead
					WHERE F3_RFC__c = :accountRFC AND RecordType.Name IN ('Seguros Prospecto') AND Status = 'Formalización y Validación'
			  ];
	}
}