temp/onboarding_retrieve/dev/objects/Lead/fields/Productos_ofertados__c.field-meta.xml
<CustomField>
    <fullName>Productos_ofertados__c</fullName>
    <label>Productos ofertados</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unidad_de_Negocio__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FONDOS DE INVERSIÓN</fullName>
            </value>
            <value>
                <fullName>BE , TDD , CHEQUERA</fullName>
            </value>
            <value>
                <fullName>MERCADO DINERO , CAPITALES, DERIVADOS</fullName>
            </value>
            <value>
                <fullName>CAMBIOS</fullName>
            </value>
            <value>
                <fullName>CREDITO</fullName>
            </value>
            <value>
                <fullName>SEGURO</fullName>
            </value>
            <value>
                <fullName>FIDEICOMISO</fullName>
            </value>
            <value>
                <fullName>ARRENDAMIENTO</fullName>
            </value>
            <value>
                <fullName>PRODCUTOS EXTRANJERO</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Dotales</fullName>
            </value>
            <value>
                <fullName>GMM</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Seguro Viaje</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
            <value>
                <fullName>Seguro PyME</fullName>
            </value>
            <value>
                <fullName>Empresarial</fullName>
            </value>
            <value>
                <fullName>01</fullName>
                <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UN PLAN PERSONAL DE RETIRO</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>CONTRATO DE MEDIACIÓN MERCANTIL PARA LA DISTRIBUCIÓN INTEGRAL DE ACCIONES DE SOCIEDADES DE INVERSIÓN Y PARA LA ADMINISTRACIÓN DE UNA CUENTA PERSONAL PARA EL AHORRO</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>CONTRATO MARCO DE COMPRAVENTA DE DIVISAS (BANCO)</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA ACTINVER)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>CONTRATO DE DEPÓSITOS BANCARIOS DE DINERO A LA VISTA PARA EL PÚBLICO EN GENERAL (CUENTA BÁSICA DE NÓMINA ACTINVER)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>TRADICIONAL DE INTERMEDIACIÓN BURSÁTIL</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>PLAN PERSONAL DE RETIRO</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>CONTRATO CUENTA LÍQUIDA ACTINVER</label>
            </value>
            <value>
                <fullName>BLINDAJE PATRIMONIAL</fullName>
                <isActive>false</isActive>
                <label>Blindaje Patrimonial</label>
            </value>
            <value>
                <fullName>PREVICANCER</fullName>
                <isActive>false</isActive>
                <label>PREVICANCER</label>
            </value>
            <value>
                <fullName>PRODUCTOS EXTRANJERO</fullName>
                <isActive>false</isActive>
                <label>PRODUCTOS EXTRANJERO</label>
            </value>
            <value>
                <fullName>Plan personal de retiro</fullName>
                <isActive>false</isActive>
                <label>Plan Personal de Retiro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

temp/onboarding_retrieve/qa/objects/Lead/fields/Sub_Ramo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Ramo__c</fullName>
    <label>Subtipo de Contrato</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Productos_ofertados__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NORMAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>SINDICATOS</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>OTRAS ENTIDADES FINANCIERAS</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>FIDEICOMISO PER MOR</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>DISTRIBUIDORES</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>FONDO AH SERIE PF</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>BANCO</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>ADMINISTRATIVO</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>PARAESTATAL</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>GOBIERNO</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>NO CONTRIBUYENTES</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>FIDEICOMISO PER FIS</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>FONDOS DE PENSIONES</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>INSTIT SEG Y FIANZAS</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>ALMACENES GRALES DE DEPOSITO</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>UNIONES DE CREDITO</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>ARRENDADORAS FINANCIERAS</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>EMPRESAS FACTORAJE FINANCIERO</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>EMPLEADO ACTINVER</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>FONDO AH SERIE PM</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CAJA AH SERIE PM</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>CAJA AH SERIE PF</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>ACTINVER FIDEICOMISO PER MOR</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>ACTINVER FIDEICOMISO PER FIS</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>CAJA AH-PF POR CTA3EROS</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>NO CONTRIB SERIE E</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CIAS SEGUROS DE PENSIONES</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SIEFORE</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>GOBIERNO SERIE E</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>FAMILAR ACTINVER</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/rollback/actipm-opportunity-listviews/deployed/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Fecha_de_Nacimiento_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento_Cliente__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PatrimConsecutivoIDLead__c.field-meta.xml
<CustomField>
    <fullName>PatrimConsecutivoIDLead__c</fullName>
    <description>Campo para almacenar el consecutivo ID al convertir el prospecto</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Consecutivo ID Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Productos_ofertados__c.field-meta.xml
<CustomField>
    <fullName>Productos_ofertados__c</fullName>
    <label>Productos ofertados</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unidad_de_Negocio__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FONDOS DE INVERSION</fullName>
                <label>Fondos de Inversión</label>
            </value>
            <value>
                <fullName>BE , TDD , CHEQUERA</fullName>
                <label>BE , TDD , Chequera</label>
            </value>
            <value>
                <fullName>MERCADO DINERO , CAPITALES, DERIVADOS</fullName>
                <label>Mercado dinero, Capitales, Derivados</label>
            </value>
            <value>
                <fullName>CAMBIOS</fullName>
                <label>Cambios</label>
            </value>
            <value>
                <fullName>CREDITO</fullName>
                <label>Credito</label>
            </value>
            <value>
                <fullName>FIDEICOMISO</fullName>
                <label>Fideicomiso</label>
            </value>
            <value>
                <fullName>ARRENDAMIENTO</fullName>
                <label>Arrendamiento</label>
            </value>
            <value>
                <fullName>PRODCUTOS EXTRANJERO</fullName>
                <label>Productos extranjero</label>
            </value>
            <value>
                <fullName>Líneas Empresariales</fullName>
            </value>
            <value>
                <fullName>Inversión Inteligente</fullName>
            </value>
            <value>
                <fullName>Seguro_Viaje</fullName>
                <label>Seguro de Viaje</label>
            </value>
            <value>
                <fullName>Vida Pagos Limitados</fullName>
            </value>
            <value>
                <fullName>Plan de Ahorro Mixto</fullName>
            </value>
            <value>
                <fullName>Plan de Ahorro Educación</fullName>
            </value>
            <value>
                <fullName>Inversión Asesorada</fullName>
            </value>
            <value>
                <fullName>Banca Soluciones</fullName>
            </value>
            <value>
                <fullName>Fondo Digital</fullName>
            </value>
            <value>
                <fullName>Pagare Platino</fullName>
            </value>
            <value>
                <fullName>Global X</fullName>
            </value>
            <value>
                <fullName>Carteras modelo</fullName>
            </value>
            <value>
                <fullName>Inversion</fullName>
            </value>
            <value>
                <fullName>PPR</fullName>
                <label>Retiro</label>
            </value>
            <value>
                <fullName>Inversion inteligente</fullName>
            </value>
            <value>
                <fullName>CD Platinum</fullName>
            </value>
            <value>
                <fullName>Cuenta Básica</fullName>
            </value>
            <value>
                <fullName>Cuenta Básica de Nómina</fullName>
            </value>
            <value>
                <fullName>Portabilidad de Nómina</fullName>
            </value>
            <value>
                <fullName>Mercado de Derivados</fullName>
            </value>
            <value>
                <fullName>Mercado de Cambios</fullName>
            </value>
            <value>
                <fullName>Cuenta Personal Especial para el Ahorro</fullName>
            </value>
            <value>
                <fullName>01</fullName>
                <label>CONTRATO MARCO DE PRODUCTOS Y SERVICIOS BANCARIOS MÚLTIPLES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTrigger_Helper_Test.cls
/** ------------------------------------------------------------------------------------------------
 * @Name     LeadTrigger_Helper_Test
 * @Author   Salvador Ramírez López (salvador.ramirez@vasscompany.com)
 * @Date     08/04/2025
 * @Group    VASS Latam
 *   ------------------------------------------------------------------------------------------------
 * @Description Clase test de la clase LeadTrigger_Helper
 * --------------------------------------------------------------------------
 * No.         Date             Author                             Description
 * 1.0         08/04/2025       salvador.ramirez@vasscompany.com   Class creation.
*--------------------------------------------------------------------------
 **/
@isTest
public class LeadTrigger_Helper_Test {
    @TestSetup
    static void makeData(){
        OD_Account_cls.bypassTriggerExecution = true;
        User objUser = LeadTrigger_Utility.updateIDAsesorToUser();
        update objUser;
        F3_Integration_Service_Settings__c objService = LeadTrigger_Utility.createService();
        insert objService;
        BranchUnit objBranch = BIT_UtilityDataTest.createBranchUnit();
        Lead objLead = LeadTrigger_Utility.createLeadRTGeneral();
        insert objLead;
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId([SELECT Id FROM LEAD LIMIT 1].Id);
        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE MasterLabel = 'Convertido'];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        lc.setDoNotCreateOpportunity(false);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        Opportunity objOpp = [SELECT ID, NAME, PatrimConsecutivoIDLead__c, Fecha_de_Nacimiento_Cliente__c FROM OPPORTUNITY WHERE ID = :lcr.getOpportunityId()];
        objOpp.PatrimConsecutivoIDLead__c = '1234';
        objOpp.Productos_ofertados__c = '01';
        objOpp.Sub_Ramo__c = '1';
        objOpp.Fecha_de_Nacimiento_Cliente__c = System.today().addYears(-40);
        update objOpp;
    }
    @isTest
    static void test_branchUnitAssignment(){
        Test.startTest();
        LeadTrigger_Helper.branchUnitAssignment([SELECT Id, RecordTypeId, OwnerId, BanqueroAsignado__c FROM LEAD LIMIT 1]);
        Test.stopTest();
    }
    @isTest
    static void test_validateMandatoryFieldsIntegrateSAP(){
        ACTINVER_UtilityFactory_utils.WrapperValueFieldSet[] lstValueFieldSet = ACTINVER_UtilityFactory_utils.getValueFieldSet('MandatoryFieldsToIntegrateSAP', 'Lead');
        Test.startTest();
        sObject sObjLead = (sObject) [SELECT Id FROM LEAD LIMIT 1][0];
        Map<String, Object> mapDataSObjectLead = sObjLead.getPopulatedFieldsAsMap();
        Lead objLead = LeadTrigger_Utility.createLeadRTGeneral();
        Boolean blnIsValidRecord = LeadTrigger_Helper.validateMandatoryFieldsIntegrateSAP(objLead,mapDataSObjectLead, lstValueFieldSet);
        Test.stopTest();
    }
    @isTest
    static void test_updateOpportunity(){
        Test.startTest();
        List<Lead> lstLead = [SELECT Id, ConvertedAccountId FROM LEAD LIMIT 1];
        LeadTrigger_Helper.updateOpportunity(lstLead[0]);
        Test.stopTest();
    }
    @isTest
    static void test_updateLead(){
        Test.startTest();
        LeadTrigger_Helper.updateLead(new List<String>{[SELECT Id FROM LEAD].Id});
        Test.stopTest();
    }
    @isTest
    static void test_getAccountByLead(){
        Test.startTest();
        LeadTrigger_Helper.getAccountByLead(new List<String>{[SELECT Id FROM LEAD LIMIT 1].Id});
        Test.stopTest();
    }
    @isTest
    static void test_getOpportunityByAccount(){
        Test.startTest();
        Opportunity objOpp = LeadTrigger_Helper.getOpportunityByAccount([SELECT ConvertedAccountId FROM LEAD WHERE IsConverted = TRUE LIMIT 1].ConvertedAccountId);
        Test.stopTest();
    }
    @isTest
    static void test_LeadsAssignmentProcess(){
        test.startTest();
        LeadTrigger_Helper.LeadsAssignmentProcess([SELECT Id, CreatedById, RecordTypeId FROM LEAD LIMIT 1]);
        test.stopTest();
    }
}